### ISSUE TITLE
Analyzing VB.net solution with loop variable declaration outside of the loop

### ISSUE THREAD

**Issue by davidthompson101** [security-code-scan/security-code-scan#1]
Hi,

We are looking at using Security-Code-Scan to provide static code analysis with security in mind, however running a scan on some legacy VB.net code I found an issue which stops the TaintAnalyzer from going through a method.

The simplest example I have boiled it down to is the ability in VB.net (though this seems impossible in C#) to declare a loop variable outside of the loop.

e.g.
the code:

     Sub Main(args As String())
        For Each argItem As String In args
            Console.WriteLine(argItem)
        Next
    End Sub

appears to be analyzed fine, however moving the declaration of argItem out of the loop as in:

    Sub Main(args As String())
        Dim argItem As String

        For Each argItem In args
            Console.WriteLine(argItem)
        Next
    End Sub

causes the error:
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzer' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method Sub Main(args As String())
        argItem As String

        For Each argItem In args
            Console.WriteLine(argItem)
        Next
    End Sub : Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.IdentifierNameSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.VariableDeclaratorSyntax'.'.	SecurityCodeScanBreaker		1	Active

![image](https://user-images.githubusercontent.com/7837521/36601834-1019b430-18ae-11e8-9ec9-9b9368ec1d5a.png)

**Comment by JarLob** [comment]
Thank you for reporting this!

**Comment by davidthompson101** [comment]
I've just updated my install through Visual Studio, and this is looking good.
Thanks for the speedy fix 👍
