### ISSUE TITLE
XSS detecting although HtmlEncode is done SCS0029

### ISSUE THREAD

**Issue by sseyalioglu** [security-code-scan/security-code-scan#105]
In the previous version, it was working fine for proper XSS handling where you can simply implement the solution in the documentation.
However after latest 3.0.0 even if you have HtmlEncode, you still receive the warning of SCS0029.

Here is the example
![image](https://user-images.githubusercontent.com/2631639/52514688-e8c21d80-2bc8-11e9-923c-0c7a0a381d1b.png)

**Comment by sseyalioglu** [comment]
A complete view of the code piece:
![image](https://user-images.githubusercontent.com/2631639/52514703-07281900-2bc9-11e9-81a7-80d5946dfbc7.png)

**Comment by JarLob** [comment]
Thanks, for the report. I'll cross reference it with #43 but will close it to keep just one tracking issue.

**Comment by JarLob** [comment]
Actually I can’t reproduce it. The case is covered in 
https://github.com/security-code-scan/security-code-scan/blob/master/SecurityCodeScan.Test/Tests/XssPreventionAnalyzerTest.cs#579
Could you simplify you function by deleting anything you don’t want to share and provide the full body?

**Comment by sseyalioglu** [comment]
First my environment. I use JetBrains Rider and MacOS 10.14.2
Here is the full method.

![image](https://user-images.githubusercontent.com/2631639/52538966-df9e9100-2d2d-11e9-8162-f37d2ff5a705.png)


As you see there is not much inside this but still having the issue.

**Comment by JarLob** [comment]
Nice to know it works on Rider! (I haven't tried it myself)
I have reproduced it, but it gives the warning not because of `user`, but because of `env.EnvironmentName`.
It is a valid bug, because there is no evidence that the environment name is an user input.
