### ISSUE TITLE
Vulnerability scans on Nuget packages used in Security Code Scan source code

### ISSUE THREAD

**Issue by eloisetaylor5693** [security-code-scan/security-code-scan#106]
There are a few products that are free for Open-Source projects which can scan the packages.config file for versions of nuget packages which have security vulnerabilities.  

Does the current CI have any such scanning?  

There are a few examples which look quite good.  But there are lots of other options too.
- https://snyk.io/plans/
- https://www.whitesourcesoftware.com/whitesource-pricing/

**Synk**
- Scans daily/weekly, and can be integrated into CI.
- Emails results.
- Can automatically create a branch + Pull request with fixes.

**White Source**

This one adds issues to the repo, with information on what the vulnerability is and how to solve it.  You can install this in the github marketplace: https://github.com/marketplace/category/continuous-integration.

Example issues that get generated: https://github.com/eloisetaylor5693/PlayNine/issues

**Comment by JarLob** [comment]
GitHub has the feature built in. Not in CI, but it scans repositories. https://help.github.com/articles/about-security-alerts-for-vulnerable-dependencies/

**Comment by eloisetaylor5693** [comment]
I noticed between the 3 options noted (github, synk and white source) they all show different package vulnerabilities. I guess they all have separate vulnerability repos
