### ISSUE TITLE
Couldnt find SQLinjection analyzer file

### ISSUE THREAD

**Issue by projectrvce** [security-code-scan/security-code-scan#108]
Where do I find the implementation of the SQLinjection rule i.e sqlinjectionanalyzer.cs file?

**Comment by JarLob** [comment]
SQl injection analyzers are implemented as a part of taint analyzer with dangerous function sinks defined in https://github.com/security-code-scan/security-code-scan/blob/master/SecurityCodeScan/Config/Main.yml Search in the file for SCS0002 for example.
