### ISSUE TITLE
XSS 

### ISSUE THREAD

**Issue by projectrvce** [security-code-scan/security-code-scan#109]
I am trying to run this project against WebGoat project mentioned in security code scan  website. I have deleted the xsspreventionanalyzer and I am still able to see the diagnostic of XSS in webgoat project. Can you please help me with this. It would really be a great help for me. Thanks in advance!

**Comment by JarLob** [comment]
@projectrvce I have a dejavu, you should have been able to learn how it works from a previous answer - https://github.com/security-code-scan/security-code-scan/issues/108

Additionally to dedicated XSS analyzer there are SCS0029 sinks in https://github.com/security-code-scan/security-code-scan/blob/master/SecurityCodeScan/Config/Main.yml for taint analyzer.

Notice that you don't need to modify SCS if you just want to disable SCS0029 warning at all, you can set Severity to None for a specific warning Id. Please see https://security-code-scan.github.io/#Severity

**Comment by projectrvce** [comment]
Okay thanks a lot! I got it now
