### ISSUE TITLE
Version 3.0 not yielding any warnings on .net core 2.2 projects

### ISSUE THREAD

**Issue by markolazic** [security-code-scan/security-code-scan#111]
I am adding SecurityCodeScan.VS2017 as a Nuget package to a .NET Core 2.2 project and running dotnet build on it, version 2.2.102. This is done on Windows 10 machine.

Running this does not yield any warnings when using version 3.0 while 2.8 does work as expected.

Simple console project made from template with added XML path injection code:
[SecurityScanBugReproduce.zip](https://github.com/security-code-scan/security-code-scan/files/3012937/SecurityScanBugReproduce.zip)

**Console output with 3.0.0 version:**
`PS C:\src\SecurityScanBugReproduce\SecurityScanBugReproduce> dotnet list .\SecurityScanBugReproduce.csproj package`
`Project 'SecurityScanBugReproduce' has the following package references`
`   [netcoreapp2.2]:`
`   Top-level Package                 Requested   Resolved`
`   > Microsoft.NETCore.App     (A)   [2.2.0, )   2.2.0`
`   > SecurityCodeScan.VS2017         3.0.0       3.0.0`

`(A) : Auto-referenced package.`
`PS C:\src\SecurityScanBugReproduce\SecurityScanBugReproduce> dotnet build`
`Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core`
`Copyright (C) Microsoft Corporation. All rights reserved.`

`  Restore completed in 53.58 ms for C:\src\SecurityScanBugReproduce\SecurityScanBugReproduce\SecurityScanBugReproduce.csproj.`
`  SecurityScanBugReproduce -> C:\src\SecurityScanBugReproduce\SecurityScanBugReproduce\bin\Debug\netcoreapp2.2\SecurityScanBugReproduce.dll`

`Build succeeded.`
`    0 Warning(s)`
`    0 Error(s)`

`Time Elapsed 00:00:01.24`

**Console output with 2.8.0 version:**
`PS C:\src\SecurityScanBugReproduce\SecurityScanBugReproduce> dotnet list .\SecurityScanBugReproduce.csproj package`
`Project 'SecurityScanBugReproduce' has the following package references`
`   [netcoreapp2.2]:`
`   Top-level Package                 Requested   Resolved`
`   > Microsoft.NETCore.App     (A)   [2.2.0, )   2.2.0`
`   > SecurityCodeScan.VS2017         2.8.0       2.8.0`

`(A) : Auto-referenced package.`
`PS C:\src\SecurityScanBugReproduce\SecurityScanBugReproduce> dotnet build`
`Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core`
`Copyright (C) Microsoft Corporation. All rights reserved.`

`  Restore completed in 49.74 ms for C:\src\SecurityScanBugReproduce\SecurityScanBugReproduce\SecurityScanBugReproduce.csproj.`
`Program.cs(12,27): warning SCS0003: XPath injection possible in 1st argument passed to 'doc.SelectNodes' [C:\src\SecurityScanBugReproduce\SecurityScanBugReproduce\SecurityScanBugReproduce.csproj]`
`  SecurityScanBugReproduce -> C:\src\SecurityScanBugReproduce\SecurityScanBugReproduce\bin\Debug\netcoreapp2.2\SecurityScanBugReproduce.dll`

`Build succeeded.`

`Program.cs(12,27): warning SCS0003: XPath injection possible in 1st argument passed to 'doc.SelectNodes' [C:\src\SecurityScanBugReproduce\SecurityScanBugReproduce\SecurityScanBugReproduce.csproj]`
`    1 Warning(s)`
`    0 Error(s)`

`Time Elapsed 00:00:01.75`

**Comment by JarLob** [comment]
To get older behavior enable [AuditMode in the configuration file](https://security-code-scan.github.io/#3.0.0).
