### ISSUE TITLE
SCS0016 with global AutoValidateAntiforgeryTokenAttribute

### ISSUE THREAD

**Issue by felickz** [security-code-scan/security-code-scan#115]
A newer pattern exists for auto validating CSRF tokens in .NET Core to protect all endpoints through global filter configuration. Is there any pattern for detecting this attribute is globally applied and disable SCS0016? Potentially here SCS0016 could apply to the use of the ignore attribute.

Filters.Add(new AutoValidateAntiforgeryTokenAttribute());

[AutoValidateAntiforgeryTokenAttribute ](https://docs.microsoft.com/en-us/dotnet/api/Microsoft.AspNetCore.Mvc.AutoValidateAntiforgeryTokenAttribute?view=aspnetcore-2.0#Remarks)can be applied as a global filter to trigger validation of antiforgery tokens by default for an application.

Also, we should call out the usage of [IgnoreAntiforgeryTokenAttribute ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.ignoreantiforgerytokenattribute?view=aspnetcore-2.0)here.

Blog explaining the topic: [https://andrewlock.net/automatically-validating-anti-forgery-tokens-in-asp-net-core-with-the-autovalidateantiforgerytokenattribute/](https://andrewlock.net/automatically-validating-anti-forgery-tokens-in-asp-net-core-with-the-autovalidateantiforgerytokenattribute/)

**Comment by JarLob** [comment]
Would be nice to have, but technically it is not supported now, i.e. it is not implemented finding the single place in the project and disabling all functions warnings based on the knowledge.
As a workaround the whole SCS0016 can be disabled if the AutoToken is set globally https://github.com/security-code-scan/security-code-scan/blob/377080aeb2bb9b091ef8f9ea8ab9d222f6881db3/SecurityCodeScan/Config/Messages.yml#L122

**Comment by sseyalioglu** [comment]
This does not make sense for webapi.

**Comment by JarLob** [comment]
As far as I know there is no warning in [ControllerBase](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase?view=aspnetcore-2.2) derived classes. Could you elaborate what doesn’t make sense?

**Comment by sseyalioglu** [comment]
Sure, when WebAPI calls other WebAPI (the called one having this control does not make sense because there is no HTML etc).

**Comment by JarLob** [comment]
I know that for WebAPI the warning makes no sense. This is why I said if your controller is derived from [ControllerBase](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase?view=aspnetcore-2.2), that doesn't have the View part, SCS shows no warning. But I'm not even sure your comment was about .NET Core. Perhaps it it would be better if you attached a sample WebApi project with a false positive example.

**Comment by sseyalioglu** [comment]
Hmm. for some reason it was derived from controller, perhaps that's why I've seen it.

**Comment by JarLob** [comment]
Closing as it unlikely to be implemented. There is a workaround to suppress the rule per project if there is a global token.

**Comment by ghost** [comment]
I am getting same error even when inherit from controllerbase with usage of [FromForm] attribute usage in parameter. Please refer attached image

![image](https://user-images.githubusercontent.com/30340103/210061012-a520af1a-e85f-413f-a9e9-bd196f449683.png)
