### ISSUE TITLE
SecurityCodeScan vs SecurityCodeScan.VS2017

### ISSUE THREAD

**Issue by robertlarkins** [security-code-scan/security-code-scan#116]
I looked through the [website](https://security-code-scan.github.io/) and I could not see any distinct information that would help me decided whether I should install either the SecurityCodeScan or the SecurityCodeScan.VS2017 Nuget Packages.

What are the main difference between these two Nuget Packages, or is it simply if I am using VS2017 or greater (I'm using VS2019), then I should just use SecurityCodeScan.VS2017?

**Comment by JarLob** [comment]
SecurityCodeScan supports VS2015, VS2017 and VS2019.
SecurityCodeScan.VS2017 supports VS2017 and VS2019.
The main difference SecurityCodeScan.VS2017 is built with .net standard, so it is Linux compatible. SecurityCodeScan is built with full .net framework and while it means it _may_ not run on Linux as far as I know it runs. Probably it depends if it hits not supported .net framework function.
