### ISSUE TITLE
CS8032: An instance of analyzer cannot be created

### ISSUE THREAD

**Issue by robertlarkins** [security-code-scan/security-code-scan#117]
I've added SecurityCodeScan v3.1.0 to three projects, and these projects are now getting CS8032 warnings:
`CS8032	An instance of analyzer SecurityCodeScan.Analyzers.CSharpAnalyzers cannot be created from C:\x\y\.nuget\packages\securitycodescan\3.1.0\analyzers\dotnet\SecurityCodeScan.dll : Exception has been thrown by the target of an invocation..`

I'm running VisualStudio 2019 with the projects targeting .NET Core 2.2.
I have the following installed:
Microsoft .NET Core Runtime - 2.2.4
Microsoft .NET Core SDK 2.2.203

How should I got about fixing these warnings? I'm unsure what other information would be helpful in this situation.

**Comment by JarLob** [comment]
This is not something I would call expected. Is there a call stack in the docked VS Errors Window if you expand the error?
I wonder if it is because of configuration file... Try installing the visual studio extension too (or try the VS extension only without adding SCS as nuget). Does it work in any of the configurations?
You could also attach a sample solution I could try.

**Comment by robertlarkins** [comment]
[CS8032.zip](https://github.com/security-code-scan/security-code-scan/files/3075241/CS8032.zip)
I took the solution I was working on and stripped it down to this, it is still generating the CS8032 warning (at least on my PC).

**Comment by JarLob** [comment]
Sorry I'm already at airport Maybe if @ViktorijaAdo has time she can look into this otherwise I’ll check it in two weeks.

**Comment by NeilBostrom** [comment]
+1 for this. Getting this on our .NET Framework project in VS2019. 3.0.0 worked fine.

**Comment by PrimeHydra** [comment]
Getting this as well, VS 2017 and a .NET Core 2.0 project.

**Comment by projectrvce** [comment]
+1 getting the same when I integrated it with sonarqube and tried running the webgoat project

**Comment by JarLob** [comment]
A new version was released. Thanks for reporting!

**Comment by jcarter777** [comment]
I am getting this error on  SecurityCodeScan.VS2019 5.2.1 (Framework 4.7.2)

CS8032
An instance of analyzer SecurityCodeScan.Analyzers.AthorizationAttributeDiagnosticAnalyzer cannot be created from 
******\packages\SecurityCodeScan.VS2019.5.2.1\analyzers\dotnet\SecurityCodeScan.VS2019.dll
Exception has been thrown by the target of an invocation

**Comment by JarLob** [comment]
Do you have a reproducible solution? See #208 and #218 for similar examples it is not necessarily this one.

**Comment by jcarter777** [comment]
I couldn't get rid of it the other day, but I'm not getting it now today. OS gunk i guess, sorry i should have waited longer before posting.

**Comment by JarLob** [comment]
Nothing to be sorry about. I'm curious to know the cause since it still happens.
