### ISSUE TITLE
SCS0018: warning not yet resolved. 

### ISSUE THREAD

**Issue by vbpradeep** [security-code-scan/security-code-scan#118]
Hi 

I have included security-code-scan on my source. i have found some issues on this, if not can you please share the solution on this.

![image](https://user-images.githubusercontent.com/12544691/56120765-7422ab00-5f8c-11e9-9957-1f100ce81bdf.png)

In above image code, i am deleting the file so i am getting the file folder path and filename, it shows vulnerability warning from  SCS. so as per solution  (https://security-code-scan.github.io/#SCS0018) i have made changes but warning not yet resolved. can you please check on this and provide solution on this.

i have used 3.0.0 version. please do needful on this

Regards,
Pradeep Kumar B

**Comment by JarLob** [comment]
You have two options:
1. Once you have added a validation, you may suppress the specific warning in the function - the warning doesn't go away automatically. See https://security-code-scan.github.io/#SuppressingandFixingtheWarnings
2. Or you can put the validation code in a dedicated function and register the function in your configuration file as described in https://security-code-scan.github.io/#Customtaintsource,sinks,sanitizersandvalidators. If everything is done correctly the warning will go away automatically. The validation function is typically used in multiple places, you need to put it in config only once.

**Comment by SapnaGoyal2020** [comment]
Me also getting same issue. Is there any other way to auto resolve warning and make code changes as per need?
![image](https://user-images.githubusercontent.com/68158307/88420765-0444d680-ce05-11ea-83ad-22cdc254ea8f.png)
