### ISSUE TITLE
Analysis on Sonarqube

### ISSUE THREAD

**Issue by ShriShalini** [security-code-scan/security-code-scan#120]
I tried adding some tainted sources and sinks and made some modification to my CSharpCodeEvaluation.cs . I created a jar file using SecurityCodeScan.nupkg and uploaded it as one of the plugins of Sonarqube. I am getting the following warning:
 CSC : warning CS8032: An instance of analyzer SecurityCodeScan.Analyzers.CSharpAnalyzers cannot be created from C:\Users\shrishalinis\AppData\Local\Temp\.sonarqube\resources\10\analyzers\dotnet\SecurityCodeScan.dll : Exception has been thrown by the target of an invocation.. [C:\Users\shrishalinis\source\repos\WebApplication1\WebApplication1\WebApplication1.csproj].
Can you please help me with solving this because I'm stuck at this for quite some time?

**Comment by JarLob** [comment]
Duplicate of #107 and #112
