### ISSUE TITLE
taint sources

### ISSUE THREAD

**Issue by projectrvce** [security-code-scan/security-code-scan#122]
hai, I have small issue regarding taint sources when StringBuilder is used instead of string for writing the query.

for example:
StringBuilder st = new StringBuilder();
st.Append("Select *from families where id = "+id); // Consider id is tainted value which comes from user input
SqlCommand(st.ToString()); // Should raise a diagnostic but doesn't raise

I tried adding the following rule in main.yml

#System.Text_StringBuilder_Append
  System.Text_StringBuilder_Append:
    Namespace: System.Text
    ClassName: StringBuilder
    Name: Append
    Method:
      Returns:
        Taint: Tainted

Can you help me in solving this so that it raises the diagnostic in SqlCommand?

**Comment by ShriShalini** [comment]
+1 Even I'm facing the same issue.

**Comment by JarLob** [comment]
Thank you for reporting. Somehow taint transfer from an argument to `this` is not implemented. I'll implement it in the next version.
