### ISSUE TITLE
SCS0007 false positive?

### ISSUE THREAD

**Issue by pedroexenberger** [security-code-scan/security-code-scan#129]
Accordingly with the [XXE Owasp cheat sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.md#xpathnavigator) the following code snippet is XXE safe.

> You can make XPathNavigator safe by giving it a safe parser like XmlReader (which is safe by default) in the XPathDocument's constructor.
> 
> Here is an example:
>```
> XmlReader reader = XmlReader.Create("example.xml");
> XPathDocument doc = new XPathDocument(reader);
> XPathNavigator nav = doc.CreateNavigator();
> string xml = nav.InnerXml.ToString();
> ```

I've created a project with the code above only, and SCS is reporting it as "XML parsing vulnerable to XXE" in the second line. Isn't that a false-positive? Thank you.

**Comment by JarLob** [comment]
Yes, a bug indeed. Although throws even before `CreateNavigator` - on creation of `XPathDocument`. I was testing only with `StringReader` and file name. Thank you for you report. I'll fix it.
