### ISSUE TITLE
SCS0015 NewtworkCredential password positional argument may be wrong

### ISSUE THREAD

**Issue by pedroexenberger** [security-code-scan/security-code-scan#130]
SCS is reporting me a SCS0015 warning when the first parameter is hard-coded (the username), instead of the second (password).

This doesn't trig anything:
`System.Net.NetworkCredential networkCredential = new NetworkCredential(getEncryptedUser(), "explicit_password");`

This does trig a SCS0015 warning:
`System.Net.NetworkCredential networkCredential = new NetworkCredential("explicit_username",getEncryptedPassword());`

Shouldn't it be the other way around? Trigger when password is explicit, but not necessarily when usernames are?

**Comment by JarLob** [comment]
Thanks, this a regression introduced by 072394fd
