### ISSUE TITLE
Correcting path-traversal warning

### ISSUE THREAD

**Issue by pedroexenberger** [security-code-scan/security-code-scan#139]
Hi,

SCS triggers me a warning for path-traversal (SCS0015) even when I use validators (E.g., assuring there is no char from Path.GetInvalidFileNameChars() in the file name, before opening a file). I had to use audit mode=true to trigger SCS0015, because otherwise SCS wasn't reporting anything, even if no validator is used and I explicitly read the filename from user (console read line, for testing).

In issue #118 @JarLob said  "Once you have added a validation, you may suppress the specific warning in the function - the warning doesn't go away automatically". This will be automated in future releases?
It would be very nice if Security Code Scan could check if the file path was previously validated to decide triggering the rule.

Thanks!

P.S.: Sorry for opening a new issue instead of replying to the closed #118 issue. I wasn't sure what was the best approach.

**Comment by JarLob** [comment]
> SCS triggers me a warning for path-traversal (SCS0015) even when I use validators (E.g., assuring there is no char from Path.GetInvalidFileNameChars() in the file name, before opening a file).

You didn't provide a code sample, so I assume you have something like:
```cs
public byte[] Download(string fileName)
{
    if (fileName.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0)
        return null;

    return System.IO.File.ReadAllBytes(Server.MapPath("~/ClientDocument/") + fileName);
}
```
`Path.GetInvalidFileNameChars()` is not a validator itself and SCS is not smart enough to understand how it was used (`if (fileName.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0)`) so the only ways are:
a) Either suppress the line `return ...`
b) Or extract the `if` into separate function like `IsSafePath` and register it as a validator in configuration file.

>  I had to use audit mode=true to trigger SCS0015, because otherwise SCS wasn't reporting anything, even if no validator is used and I explicitly read the filename from user (console read line, for testing).

By default SCS taints only input from configured [taint sources](https://github.com/security-code-scan/security-code-scan/blob/master/SecurityCodeScan/Config/Main.yml#L2849) and [taint entry points](https://github.com/security-code-scan/security-code-scan/blob/master/SecurityCodeScan/Config/Main.yml#L3697). Ideas what to add like `Console.Readline` to taint sources in default configuration are welcome.

**Comment by pedroexenberger** [comment]
Hi, 
Thank you for the detailed explanation. I'll check out approach b).
