### ISSUE TITLE
Support more async methods

### ISSUE THREAD

**Issue by Myoxocephalus** [security-code-scan/security-code-scan#140]
Hi!
Thanks for a great project!
What are the plans for more support of async methods?
My specific issue at the moment is the System.IO.File APIs that don't detect path traversal.
Example where it **detects** and warns for path traversal:
```
[HttpGet("{filename}")]
public string GetSynchronously(string filename)
{
  var content = System.IO.File.ReadAllText(filename);
  return content;
}
```
Example where it **not detects** path traversal:
```
[HttpGet("{filename}")]
public async Task<string> GetAsync(string filename)
{
  var content = await System.IO.File.ReadAllTextAsync(filename);
  return content;
}
```
If you thinks its a good idé to implement support for this i can send a PR.

**Comment by JarLob** [comment]
It was recently implemented, but accidentally not merged into Master from VS2017 branch.
