### ISSUE TITLE
SCS0027 - Open Redirect: False positive if argument is an object with a string property

### ISSUE THREAD

**Issue by speedcodenet** [security-code-scan/security-code-scan#143]
![SC0027](https://user-images.githubusercontent.com/41577088/66556168-0973b600-eb50-11e9-956c-23a0507f48ff.jpg)

**Comment by JarLob** [comment]
There is a check `Url.IsLocalUrl` in your second example, thus no warning.

**Comment by speedcodenet** [comment]
@JarLob But what about the first example? The check `Url.IsLocalUrl` is there too.

**Comment by JarLob** [comment]
Sorry, misread that.
