### ISSUE TITLE
Using discards threw an exception (C#7 / .NetCore 2.2)

### ISSUE THREAD

**Issue by djhvscf** [security-code-scan/security-code-scan#146]
Hi team, 

Using discards like 

```cs
_ = this.GetMyValue(mystring, out var yourstring);
```

is throwing the following exception: 

Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method your method MyMethod: Object reference not set to an instance of an object.'.

**Comment by JarLob** [comment]
Thanks, will look into this next week.

**Comment by JarLob** [comment]
So I have added the test: https://github.com/security-code-scan/security-code-scan/blob/da8d3f3c37b6d8cda4aec294d0aa025192296bf4/SecurityCodeScan.Test/Tests/Taint/TaintAnalyzerTest.cs#L2902-L2947 to VS2017 branch (the older Roslyn engine doesn't support discards) and fixed a bug how `out var` declaration was handled. But it wasn't throwing any exceptions.

What version of SCS and VS do you use? Could you attach a small project to reproduce the issue?

**Comment by djhvscf** [comment]
Version SCS 2.8.0
VS: 2019 (16.3.6)

Let me know if the project is still required and I will prepare something for you

**Comment by JarLob** [comment]
Oh, but why? There were many releases after 2.8. Also there are two branches: Master for >= VS2015 and VS2017 for >= VS2017. Could you try upgrading to VS2017.3.3.0 or even better the latest dev build from https://ci.appveyor.com/project/JarLob/security-code-scan/builds/29029763/job/4urc8ue5nf8og5pe/artifacts?
P.S. Keep in mind the breaking changes between 2.8 and 3.3 if you use custom configuration files. https://security-code-scan.github.io/#ReleaseNotes

**Comment by djhvscf** [comment]
Using latest version fix the issue. Thanks @JarLob
