### ISSUE TITLE
SCS0029 - XSS triggers a warn for some html encoders

### ISSUE THREAD

**Issue by pedroexenberger** [security-code-scan/security-code-scan#147]
Hi all, 
I noted rule SCS0029 (XSS) triggers a warn even though some html encoder is used. 
Below there is a code snippet to exemplify. Only Microsoft.Security.Application.Encoder.HtmlEncode is considered a solution for the xss problem, even though the other two methods also prevent xss (or doesn't?). I noted the first is referred in the [Config/Main.yml](https://github.com/security-code-scan/security-code-scan/blob/792c265cd218ea7abb8433d52ca159eb90ab91ae/SecurityCodeScan/Config/Main.yml#L319) file, but the last two are not, which may explain the behavior.

```
public MethodWithHtmlEncoders()
{
	//SCS0029
	//Does not trigger, as expected.
	string variable1 = HttpContext.Current.Request.QueryString["variable1"];
	nome = Microsoft.Security.Application.Encoder.HtmlEncode(variable2);
	HttpContext.Current.Response.Write("Hello " + variable1);

	//Does trigger (wrong?)
	string variable2 = HttpContext.Current.Request.QueryString["variable2"];
	variable2 = HttpUtility.HtmlEncode(variable2);
	HttpContext.Current.Response.Write("Hello " + variable2);

	//Does trigger (wrong?)
	string variable3 = HttpContext.Current.Request.QueryString["variable3"];
	variable3 = System.Web.Security.AntiXss.AntiXssEncoder.HtmlEncode(variable3, true);
	HttpContext.Current.Response.Write("Hello " + variable3);
}
```

I think it would be nice to have these other encoders considered for future releases if they seem appropriate. In time, thank you for maintaining this project!

Regards.

**Comment by JarLob** [comment]
Thanks, I have added them into the main config.
