### ISSUE TITLE
SCS0029 - XSS - HttpUtility.HtmlEncode solution is not recognized

### ISSUE THREAD

**Issue by jgauthier78** [security-code-scan/security-code-scan#148]
**Environment (please complete the following information):**
 - Version: 3.3.0
 - SCS0029
 - Visual Studio: 2017
 - OS: Windows 10

**Describe the bug**
Once I get the "SCS0029 - Potential XSS vulnerability" error, I still get it even if I apply the proposed 
solution =add/invoke HttpUtility.HtmlEncode

**Repro**
If possible attach a Visual Studio project that reproduces the bug. Otherwise provide a code snippet or a screenshot.
In addition, it seems that AntiXssEncoder.HtmlEncode should be used instead of HttpUtility.HtmlEncode but I can't find some trusted article that would confirm (or not) this.
Could you please give your vision? Thanks

**Code snippet**
![SCS0029](https://user-images.githubusercontent.com/8382042/71675662-8e9cee80-2d7e-11ea-8b39-ca5580311993.png)

**Comment by JarLob** [comment]
I'm a bit lost: both `HttpUtility.HtmlEncode` and `AntiXssEncoder.HtmlEncode` were added in a not yet released version - https://ci.appveyor.com/project/JarLob/security-code-scan/build/job/72n807xi9dxk007x/artifacts So both of them should not work if you use the official release 3.3.0

**Comment by jgauthier78** [comment]
Hi Jaroslav, thanks for your quick answer.
Sorry I'm also a bit lost (we're probably not on the same page ;)
See screenshot below, I understand from your comment that 3.3.0 release does not "contain" both HttpUtility.HtmlEncode and AntiXssEncoder.HtmlEncode, but is it normal to have a raised warning and an hyperlink pointing to a solution telling to use HttpUtility.HtmlEncode?
If I well understood, this is considered as a normal behavior and already planned in a coming version? If so let's simply cancel/close this issue. Maybe you have / would prefer using another channel for such discussion? Sorry to disturb you.
![SecureCodeScan](https://user-images.githubusercontent.com/8382042/71711823-07458e80-2e03-11ea-9e50-fec51824947d.png)

**Comment by JarLob** [comment]
Now I better understand what you mean... Could you please try the latest version from the link I have posted above?

**Comment by jgauthier78** [comment]
Ok thanks I'll try.
I was wondering why I could have two links each time, could you please let me know where I can check and remove one version? Thanks

**Comment by JarLob** [comment]
It is in your screenshot: Security Code Scan and Security Code Scan (for VS2017 and newer) installed extensions. Remove both. Install vsix from the link.

**Comment by jgauthier78** [comment]
It worked, perfect! Thanks for your time :) 
I could see that version number still display 3.3.0, do you plan to deliver a new version? How can I keep track of this please? Thanks

**Comment by JarLob** [comment]
Yes, I plan to bump to 3.4.0 and release a new version this week. Visual Studio will identify the newer version of extension automatically.
