### ISSUE TITLE
Add XmlPathDocument example to SCS0007 - XML eXternal Entity Injection (XXE) warning

### ISSUE THREAD

**Issue by joseph-kaainoa** [security-code-scan/security-code-scan#156]
The analyzer warns correctly, but the documentation for SCS0007 only has guidance for XmlReader and XmlDocument.  The warning also appears for XmlPathDocument/XPathNavigator, which is also insecure by default on .NET version prior to 4.5.2.  https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.md#xpathnavigator has guidance on an example fix of passing an XmlReader to XPathDocument instead of directly passing the path to XPathDocument.  This would make it obvious that these objects are also affected.

**Comment by JarLob** [comment]
Thank you for the link to an example with XPathDocument. Would you like to make a pull request with the changes to https://github.com/security-code-scan/security-code-scan/blob/master/website/rules/0007.md?
As a side note the SCS0007 warning has many more cases. You can see all of them in https://github.com/security-code-scan/security-code-scan/blob/master/SecurityCodeScan/Analyzers/XxeAnalyzer.cs

**Comment by joseph-kaainoa** [comment]
Thanks for the links, I was kind of poking around in the source, but that's more precise.  I'll check that out.

**Comment by JarLob** [comment]
Regarding the documentation. VS provides this functionality to open an associated URL when clicked on a warning. It would be unwise to not use it. Also having some longer explanation than in the description is nice especially for a developer that sees the warning for the first time and is wondering what is it about. Said that there is no intention to duplicate too much information that is available in the external links.
