### ISSUE TITLE
Usage in .Net Standard Libary

### ISSUE THREAD

**Issue by TrueGeek** [security-code-scan/security-code-scan#159]
**Environment (please complete the following information):**
 - Version: 3.5.0
 - Branch: SCS (Nuget)
 - Visual Studio: 2019 (8.5.1 build 42)
 - OS: Mac

**Describe the bug**
I have a Xamarin.Forms project. I've installed SecurityCodeScan to all projects (except the UI test project) via Nuget. It doesn't appear to be doing anything. I had StyleCop.Analyzers also installed so I've removed that to see if that helps.

I've added a SecurityCodeScan.config.yml file:

```
Version: 2.1
ReportAnalysisCompletion: true
AuditMode: true
```

And I tried some code that should cause an error:

```
var input = "x";

var p = new System.Diagnostics.Process();
p.StartInfo.FileName = "exportLegacy.exe";
p.StartInfo.Arguments = " -user " + input + " -role user";
p.Start();
```

But so far no luck. When I run a build it doesn't show any errors or warnings.

The shared code is in a .Net Standard 2.1 Library.

Thanks for any tips!

**Comment by JarLob** [comment]
It's odd `ReportAnalysisCompletion` doesn't give a `SCS0000`. I  have noticed the were changes to analysis settings in vs2019. Check if `Options->Text Editor->C#->Advanced` Background Analysis is set to `Entire Solution`... 

As a side note, the sample will not trigger a warning because `input` is constant. Better to write it as:
```cs
private static void Main(string[] args)
{
    var p = new System.Diagnostics.Process();
    p.StartInfo.FileName = "exportLegacy.exe";
    p.StartInfo.Arguments = " -user " + args[0] + " -role user";
    p.Start();
}
```

**Comment by JarLob** [comment]
Oh, I am sorry for not noticing it, but you are on Mac. For some reason VS for Mac is a different breed https://developercommunity.visualstudio.com/idea/776019/feature-request-roslyn-analyzers-support-in-visual.html Not sure what is UX on Mac when user specifically installs analyzer nuget :(
