### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by oleg-shilo** [security-code-scan/security-code-scan#160]
First of all, great product. Txs.

Now the question. Are you guys releasing this product under any more permissive license (e.g. MIT)?

Your current LGPL license is arguably more protective than you need. It is not a linkable library but a tool. By using over restrictive license you are limiting your audience without gaining anything really.

Of course it is your choice....

**Comment by JarLob** [comment]
I wonder what the use case scenario you mentioned. Multi engine scanning tool?

**Comment by oleg-shilo** [comment]
I am considering the use of your scanner for our company as a post build step during the release.
Being in the highly regulated industry (Healthcare) our tools require meticulous compliance with licensing 

We will have difficult time (when we are audited) that you did not ask us to disclose our solution source code:

![image](https://user-images.githubusercontent.com/16729806/78760295-49630b00-79c4-11ea-8699-312cf30d62d0.png)

**Comment by JarLob** [comment]
I don't think there is any issue using LPGL software for internal needs. https://stackoverflow.com/questions/1492687/using-gpl-3rd-party-code-for-internal-closed-source-project

**Comment by oleg-shilo** [comment]
Good point. Txs.

Then another question. Do you guys have anywhere an expression of your roadmap. Something like:
- every year/quarter/month the analysis rules are reviewed and updated to reflect the latest vulnerabilities and cybersecurity trends

**Comment by JarLob** [comment]
Honestly, it is not linux kernel level open source project. It is a hobby project. From time to time there are bigger contributors, but overall it is a single developer project. So there is no a roadmap. Sorry.

**Comment by oleg-shilo** [comment]
Understood. Not a problem. 

Good project though :)
