### ISSUE TITLE
Integration into CI/CD as command line/post build script

### ISSUE THREAD

**Issue by abhijitparkhi1983** [security-code-scan/security-code-scan#161]
Sorry for not using the format you guys have given. Thats because this is not a bug. But wanted to understand the way the tool can be used. 

So we have multiple C# and VB.NET projects build on .NET standard and .NET Core. We use git's pull request feature for every commit. The pull request triggers a Jenkins build process. 

We would like to explore a possibility of running security-code-scan as a post build step as a command line step. Like say giving the .sln path as a parameter to say a dotnet command which runs secuirty-code-scan on the entire solution.

We dont want to add the nugget to each and every project that we have.
I haven't seen any document / guidance on such a usage.  Is it possible ?

**Comment by abhijitparkhi1983** [comment]
The document does mention "If the CI server of your choice is using MSBuild, then integration of SCS is just a matter of adding NuGet packages and collecting the output from the build. SCS warnings are in the form of"
But there isnt any command mentioned. Please guide through it

**Comment by JarLob** [comment]
Imho everything is in Continuous Integration Builds section already. `dotnet add src/SourcesFolderName/ProjectName.csproj package SecurityCodeScanVS2017` and `dotnet build`. You can add the nuget to all projects by script. There is no other inegration outside Visual Studio afaik.

**Comment by emmcardenas** [comment]
i'm excuting `dotnet add src/SourceFolderName/ProjectName.csproj package SecurityCodeScan --version 3.5.0` and works fine with dotnet 2.2. But when i run it with dotnet 3.1 it doesn't find vulnerabilities

**Comment by eloisetaylor5693** [comment]
Could create an Azure Devops (and other build tools) task so that the results can be reported nicely, when looking at the build output.  Some extensions add another tab to the build information.

**Comment by JarLob** [comment]
@eloisetaylor5693 I'm not sure how to read your message: as "everything works, here is how to do it", suggestion for improvement or are you volunteering :)
@emmcardenas It is a bad practice to hijack unrelated threads. Try `dotnet build --no-incremental` instead.

**Comment by JarLob** [comment]
A [GitHub Action](https://github.com/marketplace/actions/securitycodescan) was implemented

**Comment by SPoint42** [comment]
This is great, but if you don't use gitlab action, there is no other solution else than writing a script to | to produce sarif or json. 

Is there a plan to add a --json or a --sarif option to produce an output file ?

**Comment by JarLob** [comment]
GitLab? Anyway there are extensions for both [GitHub](https://github.com/marketplace/actions/securitycodescan) and [GitLab](https://docs.gitlab.com/ee/user/application_security/sast/analyzers.html).
For the GitHub action just add a step you need (like saving to artifacts) before the `upload-sarif` action:

```yaml
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1.3

      # sarif files are here by default
      - run: ls ../results 
        
      - name: Upload sarif	
        uses: github/codeql-action/upload-sarif@v1
```

I do plan to add --sarif option to the [Stand-alone runner](https://www.nuget.org/packages/security-scan/), but frankly saying do not understand where and how to add the --sarif option to the [Visual Studio extension](https://marketplace.visualstudio.com/items?itemName=JaroslavLobacevski.SecurityCodeScanVS2019) or the [NuGet package](https://www.nuget.org/packages/SecurityCodeScan.VS2019/).

**Comment by SPoint42** [comment]
Sorry I was thinking Github and not gitlab :) 

If we have a --sarif or a --json, we could put the result in DefectDojo (as a central vuln) and I will write the parser if needed to import the scan result.

**Comment by JarLob** [comment]
So how do you run SCS?

**Comment by SPoint42** [comment]
I use like this . 

```
dotnet tool install --global security-scan
export PATH="$PATH:/automation/.dotnet/tools" ; export solutionPath="$(ls *.sln | sort -n | head -1)" ; security-scan $solutionPath | analyzeSCS.py
```


analyzeSCS.py find the output, generate a "defectdojo" finding and put it in REST to my DefectDojo instance. But I could be better just to send a file, as when I have a lot of finding in the result of SCS i just send 1 REST call to the Dojo

**Comment by JarLob** [comment]
It means standalone tool. Yes, it will be possible in the next version. Because in VS extension or NuGet package case the runner is VS or msbuild and the only way to request sarif if by modification of csproj or setting msbuild property.
Note though, that for standalone tool you still need the script and don't forget to restore packages, otherwise you'll get only a fraction of warnings.

**Comment by SPoint42** [comment]
I do the restore but, dit not mention if because some specific line to me
