### ISSUE TITLE
SCS0026 rule data flow depth

### ISSUE THREAD

**Issue by wesself** [security-code-scan/security-code-scan#162]
**Environment (please complete the following information):**
 - Version [e.g. 3.5.0]
 - Branch SCS
 - Visual Studio 2019 (16.5.1)
 - OS: Windows

**Describe the bug**
SCS0026 rule 
As per the image you can see the analyzer is not applying the check in nested code as with the same code above the get data method.
![image](https://user-images.githubusercontent.com/53283809/79279641-7740c780-7e7c-11ea-8e12-13896009f4e4.png)

Is there a way to set the depth of the data flow analysis as per this [sample ](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#dataflow-analysis)

**Repro**
`
public IActionResult Index(string Input)
        {
            

            using (SqlConnection connection = new SqlConnection(""))
            {
                SqlCommand sqlCommand = new SqlCommand()
                {
                    CommandText = "SELECT ProductId FROM Products WHERE ProductName = '" + Input + "'",
                    CommandType = CommandType.Text,
                };

                SqlDataReader reader = sqlCommand.ExecuteReader();
            }

            var result = GetDate(Input);

            return View();
        }

        private string GetDate(string Input)
        {
            using (SqlConnection connection = new SqlConnection(""))
            {
                SqlCommand sqlCommand = new SqlCommand()
                {
                    CommandText = "SELECT ProductId FROM Products WHERE ProductName = '" + Input + "'",
                    CommandType = CommandType.Text,
                };

                SqlDataReader reader = sqlCommand.ExecuteReader();
            }

            return "";
        }
`

**Comment by JarLob** [comment]
No such setting is available at the moment. Only `AuditMode` that treats all parameters as untrusted.
However thank you for the link, I'll investigate in a free time what's new is available in Roslyn.
Dup of #110
