### ISSUE TITLE
AD0001 using 2017 extension

### ISSUE THREAD

**Issue by mrstarware** [security-code-scan/security-code-scan#164]
**Environment (please complete the following information):**
 - Version [e.g. 3.3.0] latest/3.5
 - Branch [SCS or SCS2017] SCS for 2017 extension
 - Visual Studio [e.g. 2019 (16.3.6)] 2019 (16.5.3) (to a lesser degree vs2017)
 - OS: [e.g. Windows, Linux] Windows 10

**Describe the bug**
In my project (sorry sensitive corporate, can't share source). 
I have started getting (previously was not) AD0001 

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'SecurityCodeScan.Analyzers.CSharpAnalyzers' threw an exception of type 'System.MissingMethodException' with message 'Method not found: 'YamlDotNet.Serialization.IDeserializer YamlDotNet.Serialization.DeserializerBuilder.Build()'.'.	KUPay.Services		1	Active	Analyzer 'SecurityCodeScan.Analyzers.CSharpAnalyzers' threw the following exception:
'System.MissingMethodException: Method not found: 'YamlDotNet.Serialization.IDeserializer YamlDotNet.Serialization.DeserializerBuilder.Build()'.
   at SecurityCodeScan.Config.ConfigurationReader.DeserializeAndValidate[T](StreamReader reader)
   at SecurityCodeScan.Config.ConfigurationReader.GetBuiltinConfiguration()
   at SecurityCodeScan.Config.ConfigurationManager.<>c.<.cctor>b__8_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at SecurityCodeScan.Config.ConfigurationManager.GetBuiltInAndUserConfiguration()
   at SecurityCodeScan.Analyzers.Analyzers.Initialize(AnalysisContext analysisContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteInitializeMethod>b__41_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)

When I attempted to debug using the SCS source
It appeared the error was coming from ConfigurationManager.cs lines 41 & 51
Visual studio 2017 mostly works. It will still give AD0001 but will also give the security errors as expected, so I'd say 2017 is *mostly* working.

**Repro**
If possible attach a Visual Studio project that reproduces the bug. Otherwise provide a code snippet or a screenshot.
![image](https://user-images.githubusercontent.com/12076933/80400130-375fe400-886f-11ea-9ed8-39dc654ff112.png)

**Comment by JarLob** [comment]
Hi, sorry for delay. Does it happen with any solution or just a specific one? My only guess is there is a conflict with other version of YamlDotNet assembly. Could you please you check the following:
1. Build on other machine.
2. Search for YamlDotNet.dll and check their versions in `packages` folder of the solution.
3. Removing other visual studio extensions.

If you could tell me if 1. or 3. worked or you found other YamlDotNet.dll versions, that would help diagnosing the issue.

**Comment by JarLob** [comment]
BTW, I was able to reproduce it by installing SCS 3.5 and SCS.VS2017 2.8 in the same Visual Studio.
Make sure you have installed either SCS or SCS.VS2017.

**Comment by JarLob** [comment]
Should be fixed by https://github.com/security-code-scan/security-code-scan/commit/bfd7677a2e914e623d752a89422223b4d92a092f

**Comment by mrstarware** [comment]
@JarLob Thank you! 
I just tried with version 3.5.2 and the issue is gone :)
