### ISSUE TITLE
False positive on EF 3.1 using ExecuteSqlInterpolated

### ISSUE THREAD

**Issue by MigueZS** [security-code-scan/security-code-scan#167]
Environment
 - Version 3.5.2
 - Visual Studio 2019

On EF 3.1, ExecuteSqlInterpolated receives a FormattedString as a parameter instead of a raw string. They did this change to avoid SQL Injection by deriving the parameters from the formatted string. The library detects it as SQL Injection.

    public void Method(string parameter)
    {
        _context.Database.ExecuteSqlInterpolated($"SELECT * FROM X WHERE Id = {parameter}");
    }

That is supposed to be safe since it is automatically translated to a query with parameters and the library is detecting it as non safe.

Please correct me if I am wrong but since they are supposed to be safe this lines should be removed from the configuration file:

    RelationalDatabaseFacadeExtensions_ExecuteSqlInterpolated:
      Namespace: Microsoft.EntityFrameworkCore
      ClassName: RelationalDatabaseFacadeExtensions
      Name: ExecuteSqlInterpolated
      Method:
        InjectableArguments: [SCS0035: 1]

    RelationalDatabaseFacadeExtensions_ExecuteSqlInterpolatedAsync:
      Namespace: Microsoft.EntityFrameworkCore
      ClassName: RelationalDatabaseFacadeExtensions
      Name: ExecuteSqlInterpolatedAsync
      Method:
        InjectableArguments: [SCS0035: 1]

    RelationalQueryableExtensions_FromSqlInterpolated:
      Namespace: Microsoft.EntityFrameworkCore
      ClassName: RelationalQueryableExtensions
      Name: FromSqlInterpolated
      Method:
        InjectableArguments: [SCS0035: 1]

They were introduced [here](https://github.com/security-code-scan/security-code-scan/commit/584603f2b50568f563d862d61e64ee8725aaeb8a#diff-34b8f54577569f3aae468b7f58cc5d02) to fix the FromSqlRaw call.

**Comment by JarLob** [comment]
Thanks for the report. I’ll see if I can distinguish different versions of the library.
Regarding overriding in local config this is supposed to work:
```yaml
RelationalDatabaseFacadeExtensions_ExecuteSqlInterpolated:

RelationalDatabaseFacadeExtensions_ExecuteSqlInterpolatedAsync:

RelationalQueryableExtensions_FromSqlInterpolated:

```

**Comment by MigueZS** [comment]
Thanks a lot for the overrides and your very quick response.

I don't think you need to differentiate the library versions at least for the "interpolated" versions since they came only in EF 3. For me the FromSqlInterpolated methods should not be validated while the FromSqlRaw methods must have the check. See the following note [here](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql) 

> Prior to version 3.0, FromSqlRaw and FromSqlInterpolated were two overloads named FromSql. For more information, see the previous versions section.

Yes, the problem to analyse could be the FromSql overloads in previous versions, but maybe that is already solved with the different overloads, so removing also this one should work.

    RelationalQueryableExtensions_FromSql_3:
      Namespace: Microsoft.EntityFrameworkCore
      ClassName: RelationalQueryableExtensions
      Name: FromSql
      Method:
        ArgTypes: (System.Linq.IQueryable, System.FormattableString, params System.Object[])
      InjectableArguments: [SCS0035: 1]

**Comment by JarLob** [comment]
You are right, the interpolated sinks were incorrect from the very beginning. The biggest pain was to upgrade unit tests for EF 3.1. Thank you for reporting!
