### ISSUE TITLE
Any way to exclude particular Web.config files?

### ISSUE THREAD

**Issue by mrstarware** [security-code-scan/security-code-scan#169]
**Environment (please complete the following information):**
 - Version [e.g. 3.3.0] 3.5.2
 - Branch [SCS or SCS2017] SCS2017
 - Visual Studio [e.g. 2019 (16.3.6)] 16.5.3
 - OS: [e.g. Windows, Linux] Windows 10

**Describe the bug**
If you set the Aspx and Web.config analyzer option. 
And also have a file such as Web.config.octo.deploy.xml
then an exception may be thrown from WebConfigAnalyzer.cs -> OnCompilationAction
Due to it picking up all files starting with "Web.config" and finding a tokenized variable such as  <myTag #{MyTag} />
Is the only way to fix this a rename of the files to exclude? Or can that be configured somehow so that we only pick up some of the config files or can exclude some?

**Comment by JarLob** [comment]
I have added a configuration option with the commit https://github.com/security-code-scan/security-code-scan/commit/632ead2e9686280e36109eb4a81c62e275d75d0d. You should be able to exclude the file by adding `SecurityCodeScan.config.yml` configuration file into your project (see https://security-code-scan.github.io/#ExternalConfigurationFiles):
```yml
Version: 2.1

WebConfigFiles: ^web\.config(?!\.octo\.deploy\.xml)
```
Please try CI build https://ci.appveyor.com/api/buildjobs/ty0bku0bggil6jtd/artifacts/SecurityCodeScan.Vsix%2Fbin%2FRelease%2FSecurityCodeScan.Vsix.vsix

**Comment by JarLob** [comment]
Or 3.5.3. that was just released.
