### ISSUE TITLE
Failed to add reference. The package 'SecurityCodeScan' tried to add a framework reference to 'System' which was not found in the GAC. 

### ISSUE THREAD

**Issue by jessehouwing** [security-code-scan/security-code-scan#171]
**Environment (please complete the following information):**
 - Version 3.3.0]
 - Branch SCS
 - Visual Studio 2019 (16.7.0-pre2.0)
 - OS: Windows

**Describe the bug**
Consistently getting this error as part of the analysis:

> Severity	Code	Description	Project	File	Line	Suppression State
> ----
> Error		Failed to add reference. The package 'SecurityCodeScan' tried to add a framework reference to 'System' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
> Object reference not set to an instance of an object.				

**Repro**
If possible attach a Visual Studio project that reproduces the bug. Otherwise provide a code snippet or a screenshot.

![image](https://user-images.githubusercontent.com/4173387/84950691-957eaa00-b0ef-11ea-8583-66204aa6d08d.png)

**Comment by JarLob** [comment]
Vs2015 branch was deprecated. Please try version 5.0.0
