### ISSUE TITLE
VB.NET "Double Nested With" Cause visual studio to crash

### ISSUE THREAD

**Issue by yongweisiong** [security-code-scan/security-code-scan#172]
**Environment (please complete the following information):**
 - Version 3.5.3
 - Branch ?
 - Visual Studio 219
 - OS: Window

**Describe the bug**
Upon the following vb.net code with "Double Nested With" using CloseXML (github Excel library)

Dim wsCampaignSummary As ClosedXML.Excel.IXLWorksheet = wb.AddWorksheet("Campaign Summary") 

 With wsCampaignSummary
            With .Cell(offsetBottom, 1)
               .SetValue("Target Based on Contacted Leads:")
               .Style.Font.SetBold(True)
            End With
 End With

**Repro**
No

**Comment by JarLob** [comment]
Thanks for reporting the crash!

I wonder what is the equivalent of this in C#.

**Comment by yongweisiong** [comment]
Sure let me know if I can help in any way

**Comment by JarLob** [comment]
Fixed in the current vs2019 branch
