### ISSUE TITLE
Create .Net core global tool

### ISSUE THREAD

**Issue by dmpe** [security-code-scan/security-code-scan#176]
**Environment (please complete the following information):**
any, in particular .net 5 on linux CI

**Describe the bug**

Would it be possible to convert this tool to .net core global tool https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools. Therefore avoiding to install this per project/solution. this would be very welcome if someone is using linux ci.

https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create

**Comment by JarLob** [comment]
Implemented in https://github.com/security-code-scan/security-code-scan/commit/61ae0a1f3b1a11aab7cf03891a80f8fe9574ead4
Available for download at https://www.nuget.org/packages/security-scan
