### ISSUE TITLE
404 on Marketplace

### ISSUE THREAD

**Issue by kbiel** [security-code-scan/security-code-scan#177]
FYI: Visual Studio Marketplace is returning 404 for both your extension builds.

[SecurityCodeScan](https://marketplace.visualstudio.com/items?itemName=JaroslavLobacevski.SecurityCodeScan)
[SecurityCodeScan for VS2017](https://marketplace.visualstudio.com/items?itemName=JaroslavLobacevski.SecurityCodeScanVS2017)

![image](https://user-images.githubusercontent.com/17048116/100009841-61459e80-2d9d-11eb-9ee6-fad560dc9a4a.png)

**Comment by JarLob** [comment]
Thanks!
I have sent an email to marketplace asking what happened.

**Comment by kbiel** [comment]
@JarLob Any response from marketplace? Anything I can do to help?

**Comment by JarLob** [comment]
Thanks for reporting, that was the biggest help!
A scammer was able to add himself as a co-publisher of the extensions and deleted it from the marketplace. MS is investigating it internally and is slow to restore it. You can still download the extension from https://github.com/security-code-scan/security-code-scan/releases/tag/3.5.3 as a workaround :/

**Comment by JarLob** [comment]
The extensions have been restored.
