### ISSUE TITLE
False positive SCS0012 on HttpGet MVC Action 

### ISSUE THREAD

**Issue by madhon** [security-code-scan/security-code-scan#182]
- Version 5.0.0
 - Branch SCS2019
 - Visual Studio 2019  v16.8.5
- OS: Windows and Linux

The following simple controller action just does a get, don't think it would be affected by SCS0012 as there's no http post happening on it

[HttpGet()]
public IActionResult Index() => View();

**Comment by JarLob** [comment]
Rules for authorization check are described in https://github.com/security-code-scan/security-code-scan/blob/vs2019/SecurityCodeScan/Config/Main.yml#L2500 For example it doesn't give a warning if AllowAnonymous attribute is set.
On one hand the rule probably will create some noise in simple application, but on the other hand unauthorized access to logs on Get could be a valid issue.
What do you think? It is possible to have per user/project configuration too.

**Comment by madhon** [comment]
Wouldn't it only be an issue if authorization is in use though ? In my case its a very simple internal only site which doesn't need it. Maybe it just needs a few notes in the documentation saying that its only relevant really if authorisation attributes are in use ?

**Comment by JarLob** [comment]
You can disable the specific rule in the project settings or add AllowAnonymousAttribute to the controllers. Both options are valid if this an internal app.

**Comment by madhon** [comment]
I've used the AllowAnonymousAttribute now that I know the reason the rule triggered, thanks for help
