### ISSUE TITLE
[Improvement] Output the CWE in the reporting

### ISSUE THREAD

**Issue by SPoint42** [security-code-scan/security-code-scan#184]
**Environment (please complete the following information):**
 - Version : latest
 - Branch: SecurityCodeScan
 - Standalone tool security-scan
 - OS: Linux

**Describe the bug**

Actually in the output we printed the Rule who have match, I could be great to print the CWE ID 
Example of an actual output : 
```
Security Code Scan: mysuperfile.cs(37,24): error SCS0012: Controller method is potentially vulnerable to authorization bypass.
```
Example of an expected output with CWE
```
Security Code Scan: mysuperfile.cs(37,24): error SCS0012: CWE-ID 284: Controller method is potentially vulnerable to authorization bypass.
```

**Comment by JarLob** [comment]
Could you provide a mapping for existing SCS warning to CWEs? I wonder if it is always one to one relation though...

**Comment by SPoint42** [comment]
Yes, will do

**Comment by SPoint42** [comment]
See #185
