### ISSUE TITLE
Reciving SCS012 even though MapControllers().RequireAuthorization() is set

### ISSUE THREAD

**Issue by r3dr4gon** [security-code-scan/security-code-scan#186]
**Environment (please complete the following information):**
 - Version? **5.0.0**
 - Branch: SecurityCodeScan, SecurityCodeScan 2017, SecurityCodeScan 2019? **SecurityCodeScan 2019**
 - Visual Studio [e.g. 2019 (16.3.6)] or Standalone tool security-scan? **2019**
 - OS: Windows, Linux or Mac? **Windows**

**Describe the bug**
At startup I set:
```
  app.UseEndpoints(endpoints =>
  {
      endpoints.MapControllers().RequireAuthorization();
  });
```

Yet, I still get SCS012 warnings, unless I specifically set [Authorize] or [AllowAnonymous] above the method.

**Repro**
![image](https://user-images.githubusercontent.com/14729972/109510563-74ee5880-7aa2-11eb-90d1-b6fb88cb2eb9.png)

![image](https://user-images.githubusercontent.com/14729972/109510544-6e5fe100-7aa2-11eb-8398-bcf996410626.png)

**Comment by JarLob** [comment]
So far the authorization and CSRF analyzers do not take into account a global middleware setup. I advise to disable the SCS0012 for the whole project in your case (through rules set or editor config).
Said that SCS0012 is not quite ready for the other reasons too and will be disabled by default in the next version.

**Comment by r3dr4gon** [comment]
Gotcha, thanks for the info.
