### ISSUE TITLE
Found project reference without a matching metadata reference error running security-scan tool

### ISSUE THREAD

**Issue by devsbryan** [security-code-scan/security-code-scan#188]
Hi,

I'm running the security-scan tool in command line against a solution with .net Core and .net standard 2 projects in it.

```
dotnet tool upgrade security-scan

security-scan [solutionName].sln
```

However I get an error on one of the .net standard projects:

`Found project reference without a matching metadata reference: C:\[projectPathAndName].csproj
`

I'm doing this in an Azure DevOps pipeline but get the same issue running in powershell on my own machine - any ideas?

I thought it might be due to it being a .net standard project, but there are 2 of these type of projects and only one errors.

I see that the security-scan tool is targeting .net 5.0, but I thought this would be backward compatible?

Any help would be appreciated, the tool has already given some useful feedback but I can't seem to get it working right in the CI build :-)

**Comment by devsbryan** [comment]
I can get around this by referencing the project dependency as a nuget reference instead of a project reference. Which in this instance is arguably more correct anyway, but not sure if that would always be the case.

Will close this down as I have found a favourable workaround.

Cheers!

**Comment by JarLob** [comment]
From what I see and googled it looks like the message doesn't affect the analysis and can be ignored. It will be treated as a warning instead of error in the next version.

**Comment by devsbryan** [comment]
> From what I see and googled it looks like the message doesn't affect the analysis and can be ignored. It will be treated as a warning instead of error in the next version.

Thanks @JarLob :-)
