### ISSUE TITLE
SCS0008 and SCS0009 violations for cookie deletion but no violation for missing flags in the IDE (introduced in 5.0.1)

### ISSUE THREAD

**Issue by Piedone** [security-code-scan/security-code-scan#195]
**Environment (please complete the following information):**
 - Version? 5.1.0
 - Branch: SecurityCodeScan, SecurityCodeScan 2017, SecurityCodeScan 2019? SecurityCodeScan 2019
 - Visual Studio [e.g. 2019 (16.3.6)] or Standalone tool security-scan? Using the SecurityCodeScan.VS2019 NuGet package so I guess Standalone tool. However, I'm also working in VS 2019 (still, the analyzer violations come from the NuGet package and the SCS VS extension is not installed).
 - OS: Windows, Linux or Mac? Windows.

**Describe the bug**
SecurityCodeScan.VS2019 5.1.0 shows SCS0008 and SCS0009 violations for lines when cookies are deleted. Additionally, it doesn't show violations for `Secure` and `HttpOnly` not being set to `true` when cookies are instantiated but only in Visual Studio; during `dotnet build` those properly show up.

What I expected is that cookie deletions don't show these violations while missing flags do.

In 5.0.0 neither issues existed.

**Repro**
See this MVC `Controller` class:

![image](https://user-images.githubusercontent.com/1976647/112035939-5c70db80-8b40-11eb-9dbe-66770d720182.png)

```c#
    public class MyController : Controller
    {
        public void Index() => HttpContext.Response.Cookies.Delete("Test");
    }
```

The issue persists also if there's more code lines around the cookie-using one so it's not related to the method being a single-line expression-bodied method.

However, there's no violation for this code in the IDE:
![image](https://user-images.githubusercontent.com/1976647/112036230-abb70c00-8b40-11eb-9346-4184f1c85c7a.png)

```c#
    public static class HttpContextExtensions
    {
        public static void SetCookieForever(this HttpContext httpContext, string name, string value) =>
            httpContext.Response.Cookies.Append(name, value, new CookieOptions
            {
                Expires = DateTimeOffset.MaxValue,
            });
    }
```

It does trip during `dotnet build` though with the following:
```
E:\...\HttpContextExtensions.cs(8,62): error SCS0008: The cookie is missing 'Secure' flag.
E:\...\HttpContextExtensions.cs(8,62): error SCS0009: The cookie is missing 'HttpOnly' flag.
```

With 5.0.0 there's no issue with cookie deletion:

![image](https://user-images.githubusercontent.com/1976647/112036803-5c251000-8b41-11eb-80ce-bf30b2326798.png)

And for missing flags the violations do show up in the IDE too:
![image](https://user-images.githubusercontent.com/1976647/112036914-7363fd80-8b41-11eb-83a7-2836a8ee745d.png)

**Comment by JarLob** [comment]
This analyzer was refactored in 5.1.0 so the differences with 5.0.0 are expected.
So it boils down to two issues:
1. False positive on `Delete`. This needs to be fixed.
2. Different behavior in Visual Studio and Command line. This is something unexpected. I will try to reproduce it, but my gut feeling says there must be something additionally (disabled rule in .editorconfig or ruleset, disabled full solution analysis, hanging background analysis task, conflicting extension, etc.) - Roslyn Analyzers just simply do not behave like that.

**Comment by Piedone** [comment]
Thank you!

If it's any pointer, this happens when using our [.NET Analyzers project](https://github.com/Lombiq/.NET-Analyzers). It does include [an .editorconfig](https://github.com/Lombiq/.NET-Analyzers/blob/dev/.editorconfig) that I don't think has anything related here, as well as [a ruleset](https://github.com/Lombiq/.NET-Analyzers/blob/dev/OrchardCore.ruleset#L22) file that only disables SCS0012 (while there are multiple cascading ruleset files this is the only rule being disabled from SCS everywhere).

I tested the before/afters by changing the version on this line: https://github.com/Lombiq/.NET-Analyzers/blob/dev/Packages.props#L18 I'm using this command to build the solution:

```ps
dotnet build MySolution.sln --no-incremental -warnaserror /p:TreatWarningsAsErrors=true /p:EnforceCodeStyleInBuild=true /p:RunAnalyzersDuringBuild=true -nologo -consoleLoggerParameters:NoSummary -verbosity:quiet
```

However, due to the single version change being enough to bring out the issues I didn't want to dump this possibly superfluous information on you.

While I can't show the solution in question [this one on the selected branch](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/tree/issue/OSOE-37) also reproduces both issues (using VS 16.9.2). Just put the above-mentioned code snippets anywhere (e.g the Lombiq.TrainingDemo project is an ASP.NET Core one so all the packages are added already)

**Comment by Piedone** [comment]
Did you have a chance to look into this?

**Comment by JarLob** [comment]
Hi, I'm very sorry, I was busy and now I'm on vacations with a limited connectivity. I'll look into it after a week.

**Comment by Piedone** [comment]
Great, thank you!

**Comment by Piedone** [comment]
Thank you for fixing it!

**Comment by JarLob** [comment]
You are welcome. Try the new version. It still don't support though cases when the Expire date is set to the past with intention to invalidate the cookie.
