### ISSUE TITLE
SecurityCodeScan.V2019 fails with enforced dotnet-sdk 3.1.407 in global.json

### ISSUE THREAD

**Issue by cmenzi** [security-code-scan/security-code-scan#198]
**Environment (please complete the following information):**
 - 5.1.0
 - Branch: SecurityCodeScan 2019
 - Visual Studio 2019 (16.9.2) / dotnet sdk 3.1.407 / dotnet build
 - OS: Windows

**Describe the bug**
When adding a 'global.json' to enforce the dotnet cli to use dotnet-sdk 3.1.407, the analyzer is failing with a lot of:

```
CSC : warning CS8032: An instance of analyzer SecurityCodeScan.Analyzers.Taint.DeserializationTaintAnalyzer cannot be created from C:\Users\cmenzi\.nuget\packages\securitycodescan.vs2019\5.1.0\analyzers\dotnet\SecurityCodeScan.VS2019.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [C:\Users\cmenzi\source\repos\ClassLibrary2\ClassLibrary2.csproj]
CSC : warning CS8032: An instance of analyzer SecurityCodeScan.Analyzers.Taint.XPathTaintAnalyzer cannot be created from C:\Users\cmenzi\.nuget\packages\securitycodescan.vs2019\5.1.0\analyzers\dotnet\SecurityCodeScan.VS2019.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [C:\Users\cmenzi\source\repos\ClassLibrary2\ClassLibrary2.csproj]
...
```

Executed command: `dotnet build --force --no-incremental`

When global.json is removed or the dotnet-sdk 5.0.201 is enforced, then the analyzer works.

**Repro**

[ClassLibrary2.zip](https://github.com/security-code-scan/security-code-scan/files/6224871/ClassLibrary2.zip)

**Comment by magnusnn** [comment]
+1

**Comment by JarLob** [comment]
Looks like the error is because the analyzer references a newer version of the compiler assemblies than the build is using. Since the version has C# 9.0 support it is unlikely I'm going to downgrade the package. Maybe there is a way to include and use the assemblies in the nuget. Although they were not delivered in the nuget since the very first version and I doubt it could work. In that case the only option is to use the older version of SCS.

**Comment by JarLob** [comment]
Merging the issue with https://github.com/security-code-scan/security-code-scan/issues/200

**Comment by JarLob** [comment]
I have added a section into the documentation regarding the behavior. https://github.com/security-code-scan/security-code-scan/commit/be8b416901db6f39a9ee79aad988df938e8ead5d
