### ISSUE TITLE
MSBuild error during run of SCS

### ISSUE THREAD

**Issue by ghost** [security-code-scan/security-code-scan#199]
**Environment:**
 - Version: SecurityCodeScan 5.10 (4.x)
 - Branch: SecurityCodeScan 2019
 - MSBuild 2019 16.9.0.11203
 - OS: Windows Server 2019 and Windows 10
 - Project Target : .Net Framework 4.5.2

**Describe the bug**
Since the latest release of SCS, when I run it on my project, I got error from MSBuild (cf. screenshots below). These issues did not happen on version 5.00 of SCS.

It seems that there is an issue with MSBuild : 
`Impossible d'instancier la tâche "ResolveComReference" à partir de "Microsoft.Build.Tasks.Core, Version=15.1.0.0, 
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Impossible de charger le fichier ou l'assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou une de ses dépendances. Le fichier spécifié est introuvable.`

Which roughly translate to:
`Impossible to instantiate the task "ResolveComReference" from "Microsoft.Build.Tasks.Core, Version=15.1.0.0, 
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Impossible to charge file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. This specific file is lost.`

Nothing change neither on our project or on MSBuild.

**Repro**
I cannot provide the project, but here find the output of SCS for v5.00 and 5.10. They are in french, my apologies.

[SCS_v500.txt](https://github.com/security-code-scan/security-code-scan/files/6284766/SCS_v500.txt)
[SCS_v510.txt](https://github.com/security-code-scan/security-code-scan/files/6284767/SCS_v510.txt)

Thank you in advance for the help.

**Comment by JarLob** [comment]
Hi,
Do I understand correctly that you run https://github.com/security-code-scan/security-code-scan/releases/download/5.1.0/security-scan4x.zip? Could you try https://www.nuget.org/packages/security-scan?

**Comment by ghost** [comment]
First I used to clone the github repo and build it myself. The I use NET. 4.x (or NET Core).

However, I tried what you are suggest. I still have errors, but different:
![SCS_v510_dotnet](https://user-images.githubusercontent.com/79078843/114165968-7460a180-992d-11eb-8872-680b74436e71.png)

It says something about  "ResolveComeference" that is not supported by .NET Core and suggest to use .NET Framework of MSBuild.

Also I tried to `dotnet tool install --global security-scan --version 5.0.0` and I got the same error when running SCS. 
![SCS_v500_dotnet](https://user-images.githubusercontent.com/79078843/114166390-f3ee7080-992d-11eb-9532-393f1d2537af.png)


So now, I am confused and **I think It may not come from SCS but from my project.**

**Comment by JarLob** [comment]
It is odd it stopped working for you if nothing has changed in the project. Anyway I was planning to add a command line option to ignore msbuild errors (not all of them are really critical). Please pull and try the latest changes.
However you potentially may get not all analysis warnings if there were any project loading errors.

**Comment by ghost** [comment]
Thank you, I will try to do it. 
Another question, if I use the StandAlone runner (very cool by the way). How can I set the Audit mode? Let's say I have 5 different projects. Should I set a config file for each projetc? Or can I modify the global.config? I wonder about the best practice.

**Comment by JarLob** [comment]
Depends on you. You may set it globally in `%LocalAppData%\SecurityCodeScan\config-3.0.yml`configure every project separately or have different configs to easily pass as command line parameter. It works as layers, so command line parameter would override the globals.

**Comment by ghost** [comment]
Thank you, I think to have different configs for each parameter correspond to my need.

**Comment by ghost** [comment]
I tried to add `--ignore-msbuild-errors`, I got warnings, however it is difficult to get what it means:
![image](https://user-images.githubusercontent.com/79078843/114681752-bb281000-9d0e-11eb-8b0a-07fb334e6736.png)

Also, I change my Window's language to get errors in English. Here is an update:
![image](https://user-images.githubusercontent.com/79078843/114681940-eb6fae80-9d0e-11eb-80f3-b2f14a74a171.png)

**Comment by JarLob** [comment]
It means you have a conflicting entry for EntityFramework DbContext in your settings.yml

**Comment by ghost** [comment]
Thank you, it works fine! Except the MSBuild errors.
