### ISSUE TITLE
Error encountered during execution: The imported project "C:\Program Files\dotnet\sdk\5.0.202\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" was not found.

### ISSUE THREAD

**Issue by elle024** [security-code-scan/security-code-scan#202]
**Environment:**
 - Version: ?5.1.0?
 - Branch:
   - [X] vs2019 

 - Installation/Running method:
   - [X] Standalone tool
     - [X] DotNet Core Tool from NuGet
     - [ ] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [X] Windows

**Describe the bug**
Hi, we are using this tool do a security scan of our code using .NET 5.0 SDK. We're using dotnet command to install and execute security code scan using Azure DevOps pipeline. See YAML tasks:

- task: DotNetCoreCLI@2
  displayName: 'Install Security Code Scan'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install -g security-scan --version 5.1.1'

- task: PowerShell@2
  displayName: 'Scan build for security'
  inputs:
    targetType: 'inline'
    script: 'security-scan $(currentDir)/$(sln) --export=out.sarif -v'
    errorActionPreference: 'silentlyContinue'

However, during execution of the task 'Scan build for security', we've encountered an error below:

Msbuild failed when processing the file 'D:\a\1\s\mpf-it.onedb.sso.web\project\UBM.SSO.Presentation.Web.MVC\UBM.SSO.Presentation.Web.MVC.csproj' with message: **The imported project "C:\Program Files\dotnet\sdk\5.0.202\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\5.0.202\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" is correct, and that the file exists on disk.**  

**Repro**
If possible please attach a Visual Studio project that reproduces the bug. Otherwise provide a code snippet or a screenshot.

**Comment by JarLob** [comment]
There is https://github.com/security-code-scan/security-code-scan/blob/84e7c54640794a5caf20c5d7ce14d78ce29bf11b/SecurityCodeScan.Tool/Program.cs#L186 if you want to ignore any MSBuild errors. In VS2019 branch, not in release yet though.
