### ISSUE TITLE
SQL Injection Detection .Net Core

### ISSUE THREAD

**Issue by stefanlagrange** [security-code-scan/security-code-scan#207]
**Version**: SecurityCodeScan.VS2019 (5.1.0)
**Branch**: vs2019
**Installation/Running method**:
Visual Studio Extension
NuGet package
**Operating System**: Windows 10 (1709)
**Visual Studio**: 2019 Professional (16.9.5)
**Project Targe**t : .Net Core 3.1

This is the first time I have tried _SecurityCodeScan_ with the specific intention of detecting SQL Injection vulnerabilities.
However, so far it is not detecting anything - I have tried both the Extension and Nuget package options.

I have seen a similar issue that is marked as closed:
#150 

I am not ruling out the possibility that it is due to a configuration issue on my side.

**Microsoft.EntityFrameworkCore sample:**
`_context.Products.FromSqlRaw("SELECT * FROM [SalesLT].[Product] WHERE ProductNumber = " + productNumber);`

**Microsoft.Data.SqlClient sample:**
`var command = new SqlCommand("SELECT * FROM [SalesLT].[Product] WHERE ProductNumber = " + productNumber, connection);`

**Comment by JarLob** [comment]
There is no enough information in the sample above if the `productNumber` is untrusted input and not a number. Please see the unit tests for an examples or https://github.com/security-code-scan/security-code-scan/issues/206#issuecomment-845152616 how to mark main arguments as a untrusted data.

**Comment by stefanlagrange** [comment]
Thanks @JarLob for the quick response!

Yes, turning **AuditMode = true** is bringing back a lot more warnings, including the SQL Injection vulnerability.
So, I assume then that you need to include the _SecurityCodeScan.config.yml_ file in your solution even if you are only running the Visual Studio Extension?

I will continue to follow the comments for issue #206

**Comment by JarLob** [comment]
This is not what I meant :) The warning are shown for a tainted input. The input is tainted for example by default for `Controller` derived classes, etc. If you are playing with a console application you need add a configuration entry to taint the Main arguments. Another way to quickly test something is to modify an existing test. Most of them use tainted input.
You shouldn't use audit mode unless you want to get tons of false positives.

**Comment by stefanlagrange** [comment]
Hi @JarLob 

With a bit of trial-and-error I was able to come up with a config that, at least, does not require audit mode.
I have included more detailed code samples below.

Please note that this is just the code for the **Microsoft.Data.SqlClient** example.
The **Microsoft.EntityFrameworkCore** example is working as well.

Interface definition:
```
namespace SQLInject_Web.Repositories
{
    public interface IProductRepository
    {
        void GetProductsDirectSql(string connectionString, string productNumber);
    }
}
```

Implementation of **GetProductsDirectSql**:
```
public void GetProductsDirectSql(string connectionString, string productNumber)
{
    using (SqlConnection connection = new SqlConnection(connectionString))
    {
        var command = new SqlCommand("SELECT * FROM [SalesLT].[Product] WHERE ProductNumber = " + productNumber, connection);

        connection.Open();

        using (var reader = command.ExecuteReader())
        {
            while (reader.Read())
            {
                Console.WriteLine($"{reader[0]}, {reader[1]}");
            }
        }
    }
}
```

I simply added a reference to the Interface under the **TaintEntryPoints** in the _SecurityCodeScan.config.yml_ file:
```
Version: 3.1
ReportAnalysisCompletion: false
AuditMode: false

TaintEntryPoints:
    SQLInject_Web.Repositories.IProductRepository:
        Methods:
```
That's it!
I was a bit surprised that I did not even had to add any methods and/or sinks.
I guess the config can be tweaked a lot more from this point onwards.
