### ISSUE TITLE
SecurityCodeScan.exe process never finish

### ISSUE THREAD

**Issue by jankonikola93** [security-code-scan/security-code-scan#210]
**Environment:**
 - Version: 5.1.0
 - Branch:
   - vs2019  Both https://www.nuget.org/packages/SecurityCodeScan.VS2019 and https://www.nuget.org/packages/security-scan (DotNet Tool)
 - Installation/Running method:
   - [ ] NuGet package
   - [ ] Standalone tool
     - [ ] DotNet Core Tool from NuGet
 - Operating System:
   - [ ] Windows 10 Pro Version 10.0.19042 Build 19042

**Describe the bug**
I have installed SCS nuget package in all projects in my solution, after that I'm unable to build the solution.
Build is running but never finish. When looking in Task Manager I've notice that during this build CPU is constantly on 90% or higher, also SecurityCodeScan.exe process starts to increase RAM usage after some amount of time (3-5 minutes after running build).
The same things happens when I try to use .NET CLI tool.
When I use SCS 3.5.4 (https://www.nuget.org/packages/SecurityCodeScan/) everything works fine.

**Comment by JarLob** [comment]
Sounds like a definite bug. Do you have a repro solution or maybe your project is open source?

**Comment by jankonikola93** [comment]
No, my project is not open source. Is it ok for you if I try to debug SCS Tool when working with my solution?

**Comment by JarLob** [comment]
Sure, it is open source and allowed to be debugged :)
This link also describes how to identify the issue from logs without debugger: https://twitter.com/samharwell/status/1379468469138190337

**Comment by jankonikola93** [comment]
The problem occurs in class Runner in method GetDiagnostics, line 61.
![image](https://user-images.githubusercontent.com/41673484/120811612-74a3a480-c54c-11eb-9fd2-ccf665b842d7.png)
It's never get outside this method. I suppose that something from Roslyn analyzers causes this, but I'm not sure what exactly.
I tried MSBuild Log Viewer but there is no useful information because build never ends.

**Comment by JarLob** [comment]
Analyzers run as a step during compilation, so it basically looks like just as an entry point to `GetCompilationAsync`. 
Stack view would be better. It should give you at least Roslyn method names with properly configured PDBs (Options->Debugging->Symbols) and I also recommend debugging options like unticked "Enable Just My Code", ticked "Enable source server support",  "Enable Source Link Support", "Enable .NET framework source stepping".

Another possibility is that the actual analysis is offloaded into separate ServiceHub.RoslynCodeAnalysisService.exe process (Definitely happens in visual studio, not sure about SCS tool case). You may uncomment the lines https://github.com/security-code-scan/security-code-scan/blob/b246418f5d17ba8634ffd70295da636ee3596fc5/SecurityCodeScan/Analyzers/Analyzers.cs#L134-L135 to get a chance to attach a debugger.

HTH
