### ISSUE TITLE
Raise a warning on detection of usage of insecure configuration options

### ISSUE THREAD

**Issue by righettod** [security-code-scan/security-code-scan#212]
**Environment:**
 - Version: 5.1.1.0
 - Branch:
   - [ ] vs2019 
   - [ ] vs2017 
   - [ ] vs2015 
 - Installation/Running method:
   - [ ] Visual Studio Extension 
   - [ ] NuGet package
   - [x] Standalone tool
     - [x] DotNet Core Tool from NuGet
     - [ ] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [x] Windows
   - [ ] Linux
   - [ ] Mac

**Describe the bug**
It is not a bug but a question about the rules.
Does the scanner support adding custom rules, through the YAML file, which will trigger a warning if, for example, the code contains the use of the following option:

```csharp
IdentityModelEventSource.ShowPII = true:
```

or it is needed to implement a dedicated [Analyzer](https://github.com/security-code-scan/security-code-scan/tree/vs2019/SecurityCodeScan/Analyzers) ?

**Repro**
Not applicable

Thanks a lot for this amazing tool and thank you very much  in advance for your feedback 😃

**Comment by JarLob** [comment]
It looks similar to hardcoded credentials rules in https://github.com/security-code-scan/security-code-scan/blob/vs2019/SecurityCodeScan/Config/Main.yml

**Comment by JarLob** [comment]
Ah, but you need to flag only `true`. Then separate analyzer is better. Unless SCS adds support for it.

**Comment by righettod** [comment]
OK thank you very very much for your quick reply 👍
