### ISSUE TITLE
Document Config File Version Increment

### ISSUE THREAD

**Issue by richardlawley** [security-code-scan/security-code-scan#213]
**Environment:**
 - Version: 5.1.0
 - Branch:
   - [X] vs2019 
   - [ ] vs2017 
   - [ ] vs2015 
 - Installation/Running method:
   - [ ] Visual Studio Extension 
   - [X] NuGet package
   - [ ] Standalone tool
     - [X] DotNet Core Tool from NuGet
     - [ ] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [X] Windows
   - [ ] Linux
   - [ ] Mac

**Describe the bug**
0f0a6b17c00fbe5355deb1f003a503593eeaef8d made changes to the config file format, which broke existing builds using an external configuration file.  In addition, the documented examples for configuring AuthorizeCheck are still using the old format.  These two things meant it took me quite some time to track down the actual cause.  Builds in VS2019 using nuget would include the error message:

> CSC : error AD0001: Analyzer 'SecurityCodeScan.Analyzers.CompilationAnalyzer' threw an exception of type 'YamlDotNet.Core.YamlException' with message '(Line: 7, Col: 7, Idx: 107) - (Line: 7, Col: 7, Idx: 107): No node deserializer was able to deserialize the node into type SecurityCodeScan.Config.AttributeCheckIncludeExclude, SecurityCodeScan.VS2019, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null'.

I first made some progress when I ran the standalone tool which printed an error message about Configuration version mismatch.  This message is NOT printed in VS.

Some suggestions:
* Update documentation or release notes to indicate that the required version is now 3.1 (and describe the change to RequiredAttribute)
* Update the "Version mismatch" error message to include the expected version (e.g. Version mismatch, expected 3.1 but found 3.0)
* If enforcing exact configuration file match, then VS build should also throw this exception.

**Comment by JarLob** [comment]
Thanks for spotting this! I have updated the version check and documentation. As for what has changed the best resource of working examples is https://github.com/security-code-scan/security-code-scan/blob/vs2019/SecurityCodeScan/Config/Main.yml
