### ISSUE TITLE
.Net Framework 4.8 can't finde Sql Injection 

### ISSUE THREAD

**Issue by kkman021** [security-code-scan/security-code-scan#217]
**Environment:**
 - Version: 5.2.1
 - Installation/Running method:
   - [ ] Visual Studio Extension 
   - [ ] NuGet package
   - [ ] Standalone tool
     - [ ] DotNet Core Tool from NuGet
     - ★ security-scan4x.zip from GitHub Release section
 - Operating System:
   - ★ Windows
   - [ ] Linux
   - [ ] Mac

**Describe the bug**
I hava a sql injection command in my project.

        private static string XXFunction(long ip, string table)
        {
            var sql = "select Column1 from  " + table + "where  @IP  between  Column2  and  Column3 ";

            using (var con = new SqlConnection("Datasource....."))
            {
                con.Open();

                if (con.State == ConnectionState.Closed)
                    con.Open();

                var cmd = new SqlCommand(sql, con);

                cmd.Parameters.AddWithValue("@IP ", ip);
                cmd.CommandType = CommandType.Text;
                return cmd.ExecuteScalar() != null ? (string) cmd.ExecuteScalar() : "XX";
            }
        }

**Repro**
once i run the security-scan.exe, i expect that should find a sql injection SCS0002, but i can't find in the report.
Is there any setting i lost to config?
Thanks for you investigate.

**Comment by JarLob** [comment]
SCS tracks untrusted input from its source to the sink (new SqlCommand in this case). The sources are configured in https://github.com/security-code-scan/security-code-scan/blob/vs2019/SecurityCodeScan/Config/Main.yml#L22-L367 Make sure there is a dataflow from the untrusted input in your program. If the function is always called as `XXFunction(ip, "foo")` there is no injection.

**Comment by kkman021** [comment]
> 
> 
> SCS tracks untrusted input from its source to the sink (new SqlCommand in this case). The sources are configured in https://github.com/security-code-scan/security-code-scan/blob/vs2019/SecurityCodeScan/Config/Main.yml#L22-L367 Make sure there is a dataflow from the untrusted input in your program. If the function is always called as `XXFunction(ip, "foo")` there is no injection.

Thanks JarLob,
If there no real case to inject the sql command, and SCS will not detech?
For example:
If the table parameter is come from a Web Api request body, it will not find any sql injection issue?

I have tried change the sql command below, and it still not working

`
        table = " ' 1=1 ";
        var sql = "select Column1 from  " + table + "where  @IP  between  Column2  and  Column3 ";
`

**Comment by JarLob** [comment]
> If the table parameter is come from a Web Api request body, it will not find any sql injection issue?

It will https://github.com/security-code-scan/security-code-scan/blob/vs2019/SecurityCodeScan/Config/Main.yml#L89

> I have tried change the sql command below, and it still not working
> 
> `table = " ' 1=1 "; var sql = "select Column1 from " + table + "where @IP between Column2 and Column3 ";`

Take a look at the tests for examples https://github.com/security-code-scan/security-code-scan/blob/vs2019/SecurityCodeScan.Test/Tests/Taint/SqlInjectionAnalyzerTest.cs

I would be easier if you attach a sample project.

**Comment by kkman021** [comment]
> Take a look at the tests for examples https://github.com/security-code-scan/security-code-scan/blob/vs2019/SecurityCodeScan.Test/Tests/Taint/SqlInjectionAnalyzerTest.cs

Thanks again, this test is very helpful. I will try it.

**Comment by JarLob** [comment]
I'm closing it if there is no issue.
