### ISSUE TITLE
How to scan netframework from the cmdline?

### ISSUE THREAD

**Issue by MarlonMrN** [security-code-scan/security-code-scan#219]
**Environment:**
 - Version: ?5.1.0?
 - Branch:
   - [ ] vs2019 
   - [x] vs2017 
   - [x] vs2015 
 - Installation/Running method:
   - [ ] Visual Studio Extension 
   - [x] NuGet package
   - [ ] Standalone tool
     - [ ] DotNet Core Tool from NuGet
     - [ ] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [x] Windows
   - [ ] Linux
   - [ ] Mac

**Describe the bug**
Hi, I'm trying to scan a .netframework 4.6.1 project without visual studio. 
I used to do: -add the dependency on the project with visual studio
Use the MSBuild.exe to build the project and see the output of it. 
Something like this: (after the dependency already added from vs)
`C:\Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe -t:Clean pathtosln.sln`
and then
`C:\Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe pathtosln.sln -p:RunCodeAnalysis=true`
and I could see the reported SCS warnings.
But now, I got an error saying that this RunCodeAnalysis was deprecated 
the error message is:
`MSBUILD : warning : "Run Code Analysis" has been deprecated in favor of FxCop analyzers, which run during build. Refer to https://aka.ms/fxcopanalyzers to migrate to 
FxCop analyzers.`

I tried following the link but I got no success, do any of you know what I need to change to keep performing the scan? The build from VisualStudio still shows the SCS warnings, but I cannot make it work from the cmdline

**Comment by JarLob** [comment]
Just run "msbuild your.sln" from the project directory. Here is an example https://github.com/security-code-scan/FullDotNetWebApp
