### ISSUE TITLE
Extension consuming all available memory 

### ISSUE THREAD

**Issue by jonataspc** [security-code-scan/security-code-scan#222]
Just after updating to the latest version (https://marketplace.visualstudio.com/items?itemName=JaroslavLobacevski.SecurityCodeScanVS2019) the Visual Studio keeps consuming all available memory (process ServiceHub.RoslynCodeAnalysisService.exe). 
This behavior stops when the extension is disabled.

Microsoft Visual Studio Enterprise 2019 Version 16.10.4

![image](https://user-images.githubusercontent.com/13005203/128559873-99de9465-8e6c-4707-8f58-387ccf738627.png)

![image](https://user-images.githubusercontent.com/13005203/128560413-c17d1963-c601-41bd-b5b4-e4c2f3006d3f.png)

Any hint to solve this behavior?

**Comment by JarLob** [comment]
Does it happen in all solutions? If not a reproducible project would help. Try to unload projects one by one to narrow down the problem.
