### ISSUE TITLE
Results should be normalized for parsing

### ISSUE THREAD

**Issue by MarlonMrN** [security-code-scan/security-code-scan#223]
**Environment:**
 - Version: ?5.1.0?
 - Branch:
   - [x] vs2019 
   - [ ] vs2017 
   - [ ] vs2015 
 - Installation/Running method:
   - [ ] Visual Studio Extension 
   - [ ] NuGet package
   - [x] Standalone tool
     - [ ] DotNet Core Tool from NuGet
     - [x] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [x] Windows
   - [ ] Linux
   - [ ] Mac

**Describe the bug**
I'm trying to parse the results from the scanner, but findings from web.config don't follow the same structure as from other files.
For parsing the results, I get the output lines containing "Found: " and "SCS0"
And then I parse each individual line. 
A normal line is:
Found: {filename} : warning SCS0{vuln-code}: {message}, where this message is usually something like vuln xx found in 'code detail' causing x y z
For example:
```
Found: C:\path\WebGoat.Net\WebSite\Default.aspx.cs(13,34): warning SCS0008: The cookie is missing 'Secure' flag.
```

However, vulnerabilities found in web.config aren't reported in this format. I got:
```
Found: warning SCS0030: Request validation is enabled only for pages, not for all HTTP requests. C:\path\WebGoat.Net\WebSite\Web.config(30): <httpRuntime requestValidationMode="2.0" />.
```

An ideal way to report this would be to follow the same convention of the other findings, like this
```
Found: C:\path\WebGoat.Net\WebSite\Web.config(30): warning SCS0030: Request validation is enabled only for pages, not for all HTTP requests at/in/with ' <httpRuntime requestValidationMode="2.0" ' />.
```
Can this be normalized? 
Also, is there any other format of results I should be aware of? 
Or is there a better option to get those results for parsing? 

I rely on those outputs to be formatted the same, so I can properly parse the results and create an object with the findings informations.

**Repro**
https://github.com/ShiftAndre/WebGoat.Net
scanning with the standalone scanner for version 4.x

**Comment by MarlonMrN** [comment]
Thanks for the quick action @JarLob 

But does the commit 3b5a02d fixes the ordering of those fields?

note that the "usual" finding is: (I'm relying here on the " : " separators to get those fields)
Found: {file(line,col)} : {warning & code} : {message with finding detail + piece of code}

While the web.config finding is:
Found: {warning & code} : { message, file, code }    and this last field doesn't really have a separator to get the file name from...

**Comment by JarLob** [comment]
Just try it ;)

P.S. Friendly reminder that the tool supports exporting results to JSON (SARIF).

**Comment by MarlonMrN** [comment]
@JarLob 
I'm assuming I should test from the releases in appVeyor, am I right?

But seems like I don't have enough permissions, as I cannot see the "Configuration" so I can follow 
```Configuration: Release -> Artifacts```

**Comment by JarLob** [comment]
Verified that it is accessible from Chrome Incognito. Go to https://ci.appveyor.com/project/JarLob/security-code-scan, click on `Configuration: Release` then `Artifacts`.

**Comment by MarlonMrN** [comment]
Ops, I was searching for a kind of a button/menu... My bad @JarLob .

I've tested it and it's working flawlessly. Thanks a lot for this fix!!

**Comment by MarlonMrN** [comment]
Hello again @JarLob 
Any ideas on when this will reach an official release?

thanks!

**Comment by JarLob** [comment]
In few weeks

**Comment by MarlonMrN** [comment]
Hi @JarLob, can we get a release containing this fix?
