### ISSUE TITLE
New Release in Nuget 

### ISSUE THREAD

**Issue by MarlonMrN** [security-code-scan/security-code-scan#228]
Hi, the last release was in early July, since then, there are some bug fixes done in this repo that never reached the production release, so the version available from Nuget still faces the issues. 

Is it possible to release a new version containing the fixes?

Thanks

**Comment by JarLob** [comment]
I have started migration from appveyor to github actions. Which should fix the #196 and make releasing new builds less manual. I expect the new release tomorrow.
