### ISSUE TITLE
Which NuGet Package for VSCode?

### ISSUE THREAD

**Issue by Tiberriver256** [security-code-scan/security-code-scan#229]
The instructions on [the website](https://security-code-scan.github.io/) say to use the `SecurityCodeScan` package but if you visit the package on NuGet it says this:

![image](https://user-images.githubusercontent.com/6989492/140068233-28cc17ec-603a-4c3c-89aa-2ed9f3a7d148.png)

Should `SecurityCodeScan.VS2019` work in VSCode? I understand from #80 that VSCode and other editors supporting Roslyn analyzers should work, just not sure which package to use.

**Comment by dbalikhin** [comment]
You need to use 2019 version.
5.2.1 is the latest released version. 
https://www.nuget.org/packages/SecurityCodeScan.VS2019/5.2.1/

**Comment by JarLob** [comment]
Thank you. I have updated the web page. Please report if you find any other old reference.
