### ISSUE TITLE
security-scan: command not found on Ubuntu 20.04

### ISSUE THREAD

**Issue by abhijitparkhi1983** [security-code-scan/security-code-scan#244]
**Environment:**
 - Version: ?5.1.0?
 - Branch:
   - [x] vs2019  
 - Installation/Running method:
   - [x] Standalone tool
     - [x] DotNet Core Tool from NuGet
 - Operating System:   
   - [x] Linux

**Describe the bug**
- Installed .net 5.0 (5.0.406) on a Ubuntu 20.04 vanilla machine.
- Then using command `dotnet tool install --global security-scan` installed security-scan tool.
- Tool installs successfully. Verified it by doing cd to `cd  /home/ubuntu/.dotnet/tools` where `security-scan` is present.
- When we try to run any command with `security-scan`, we get error `security-scan: command not found`
- Completely stuck then after.

**Repro**
![image](https://user-images.githubusercontent.com/7124615/162440856-639addf9-2715-4549-a23c-fa2447d86e49.png)

**Comment by JarLob** [comment]
Duplicate of https://github.com/security-code-scan/security-code-scan/issues/226?
