### ISSUE TITLE
Not getting warnings with the sample project WebGoat.NET

### ISSUE THREAD

**Issue by mrcnee93** [security-code-scan/security-code-scan#245]
**Environment:**
 - Version: ?5.6.2?
 - Branch:
   - [X] vs2019 
   - [ ] vs2017 
   - [ ] vs2015 
 - Installation/Running method:
   - [X] Visual Studio Extension 5.6.2
   - [ ] NuGet package
   - [ ] Standalone tool
     - [ ] DotNet Core Tool from NuGet
     - [ ] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [X] Windows
   - [ ] Linux
   - [ ] Mac

**Describe the bug**
I downloaded the WebGoat.NET, the projects does not compile and after fixing the bug SecutiryCodeScan still don't show the warnings. 

**Repro**
your sample project.

i don't know how to give you more information, i'm working on a virtual machine with visual studio 2019, the SecurityCodeScan extension for vs2019 downloaded from your link and nothing else.

**Comment by JarLob** [comment]
I cannot reproduce it with VS2022. Note that the warnings in case of VS extension are shown in the "Error List" tab. Also make sure you enabled full solution analysis according to instructions. There are two [more](https://github.com/security-code-scan/DotNetCoreWebApp) [projects](https://github.com/security-code-scan/FullDotNetWebApp) you can test with.

**Comment by mrcnee93** [comment]
thanks, it was the "Entire Solution" flag indeed.
i misunderstood the docs and thought that the flag was for the NuGet Version.

thanks again for the fast reply
