### ISSUE TITLE
CLI tool prefixes findings with "Found:" which is not consistent with MSBuild output format

### ISSUE THREAD

**Issue by WaldenL** [security-code-scan/security-code-scan#271]
**Environment:**
 - Version: 5.6.7
 - Branch:
   - [X] vs2019 
   - [ ] vs2017 
   - [ ] vs2015 
 - Installation/Running method:
   - [ ] Visual Studio Extension 
   - [ ] NuGet package
   - [ ] Standalone tool
     - [ ] DotNet Core Tool from NuGet
     - [X] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [X] Windows
   - [ ] Linux
   - [ ] Mac

**Describe the bug**
The command line tool (I'm using 4.x, but would be Core as well) emits findings as "Found: File(location): Issue: Message" instead of the "standard" MSBuild format of "File(location): Issue: Message" (note the leading 'Found:' literal text). This can cause issues for automation tooling (like Jenkins) that attempts to parse these lines thinking they follow the standard MSBuild format. 

**Repro**
Output from running SCS CLI (note the 'Found: ') in the findings:
```
Loading solution 'xxx.sln'
Resolve         0:00.0771520    TimeTracker.csproj (netstandard20)
Resolve         0:00.0015349    DBSession.csproj (net48)
Resolve         0:00.0016803    Extensions.csproj (net48)
Resolve         0:00.8752894    Core.csproj (net48)
...
Finished loading solution 'xxx.sln'
Found: C:\jenkins\workspace\xxx-Dev\src\Core\User.cs(1091,36): warning SCS0005: CWE-338: Weak random number generator.
Found: C:\jenkins\workspace\xxx-Dev\src\Extensions\HttpResponseExtensions.cs(70,22): warning SCS0027: CWE-601: Potential Open Redirect vulnerability was found where 'url' in 'void HttpResponse.Redirect(string url, bool endResponse)' may be tainted by user-controlled data from 'NameValueCollection HttpRequest.QueryString' in method 'void HttpResponseExtensions.Done(HttpResponse response, string fallbackUrl)'.
...
```

**Comment by WaldenL** [comment]
Not to be that person that just complains, I'm also posting a PR with a fix. This adds a `no-finding-prefix` option to the CLI to suppress this prefix. By doing it as an option (default to keeping prefix) we don't break anything that expects the prefix but those of us that don't want it can now suppress it.

**Comment by JarLob** [comment]
Fixed in https://github.com/security-code-scan/security-code-scan/commit/021bfff6f38a7f3d3780f588ccb7c82ecd39de27
