### ISSUE TITLE
security-scan' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Ethan0007** [security-code-scan/security-code-scan#278]
**Environment:**
 - Version: ?5.1.0?
 - Branch:
   - [X] vs2019 
   - [ ] vs2017 
   - [ ] vs2015 
 - Installation/Running method:
   - [ ] Visual Studio Extension 
   - [ ] NuGet package
   - [ ] Standalone tool
     - [X] DotNet Core Tool from NuGet
     - [ ] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [X ] Windows
   - [ ] Linux
   - [ ] Mac

**Describe the bug**
Failed to scan after installing using azure pipeline.
I'm using .NET 6
Error: 'security-scan' is not recognized as an internal or external command

**Repro**
<img width="248" alt="image" src="https://user-images.githubusercontent.com/12542052/221485855-459cf181-b899-4406-9ec0-b75ac04a1611.png">
<img width="322" alt="image" src="https://user-images.githubusercontent.com/12542052/221485895-700166df-6511-456c-8e3f-58e2eb2df55b.png">

**Comment by JarLob** [comment]
A duplicate of https://github.com/security-code-scan/security-code-scan/issues/226#issuecomment-908193332?
