### ISSUE TITLE
Upload Visual Studio Code extension to Open VSX

### ISSUE THREAD

**Issue by saerosV** [security-code-scan/security-code-scan#281]
**Describe the issue**

As stated in the [Archlinux Wiki](https://wiki.archlinux.org/title/Visual_Studio_Code#Extensions_support), the open-source builds of VSCode (Code, VSCodium) don't have access to [Microsoft's Marketplace](https://marketplace.visualstudio.com/vscode). Instead, the [Open VSX](https://open-vsx.org/) registry is used.

To increase Security Code Scan's extension visibility, and facilitate users' experience, I suggest uploading the [security-code-scan](https://github.com/security-code-scan/security-code-scan) VSCode extension to the [Open VSX](https://open-vsx.org/) registry.

**Comment by JarLob** [comment]
There is no official Security Code Scan support for VSCode. The VSIX is for Visual Studio.
