### ISSUE TITLE
Some Security Warnings in VSTS Build Overview missing

### ISSUE THREAD

**Issue by mpdeimos** [security-code-scan/security-code-scan#46]
First, thanks for the effort building a free library with some security related checks :+1: 

I want to get an overview of all security warnings in a project. For prototyping this I've created a VSTS build for the WebGoat.NET sample project. The analyzer is picked up fine and I get the 22 expected errors in the detailed log:

![screenshot from 2018-05-09 11-34-45](https://user-images.githubusercontent.com/644735/39807896-ce3e3b5c-537d-11e8-81ff-790240881b80.png)

When taking a look at the Build overview, I'm missing however half of the warnings:

![screenshot from 2018-05-09 11-35-09](https://user-images.githubusercontent.com/644735/39807946-ebb83598-537d-11e8-8856-b114eeea573a.png)

I'm not sure whether this is a configuration issue on my side or something wrong in VSTS. Do you have any experience with this?

**Comment by JarLob** [comment]
Is Build Overview an VSTS feature? Sorry, I have no experience with VSTS. Since analyzers are built in to msbuild I don't see why it should be different...
However I have a plan to investigate VSTS extensions in couple of next months, so I'll keep the issue as a reminder to look for.

**Comment by mpdeimos** [comment]
Yea, that's an excerpt of the page that opens when clicking on the Build#. I'll also investigate further and try to find some workarounds :)

**Comment by MarekBylica** [comment]
Hey!
I don't want to open a new issue, because my issue is quite similar but it happens in TFS.
Even if I have a configuration done for each project and its build I can see no SCS warnings in build "Summary" or even in the full log files which are downloadable. Code analysis is enabled for every project and platform in properties. In Visual Studio everything works great. Am I missing something?

**Comment by JarLob** [comment]
I don't know. Unfortunately no progress on this.

**Comment by JarLob** [comment]
Hi, could you please give a try to the new release 3.2.0?
