### ISSUE TITLE
Support for analyzing a combination of .NET Framework and .NET Core based applications on Ubuntu

### ISSUE THREAD

**Issue by abhijitparkhi1983** [security-code-scan/security-code-scan#78]
We have recently started looking into using .NET Core for developing our future code bases. 
As far as our understanding goes, there is no way to compile the .NET framework based applications on Ubuntu platform. Only the .NET Core based applications can be compiled on Ubuntu.

But because security-code-scan appears to be a static code analyzer which does not depend on code compilation,  is it possible that we can still run security-code-scan on a application code which is a combination of .NET core and .NET Framework based source codes on Ubuntu environment ?

**Comment by JarLob** [comment]
SCS is an extension for Roslyn - C# compiler. As far as I know Mono is the best option to build .NET framework applications on Linux. It doesn't implement 100% features of the framework though, but even it doesn't compile you may still get partial analysis results.
