### ISSUE TITLE
Feature Request: Add support for Visual Studio Code

### ISSUE THREAD

**Issue by mtausig** [security-code-scan/security-code-scan#80]
It would be great if there was not only a Visual Studio but also a Visual Studio Code extension for this software. That way, it would also be usable in Linux.

**Comment by JarLob** [comment]
There is a pull request in progress to OmniSharp to support all Roslyn based analyzers - https://github.com/OmniSharp/omnisharp-roslyn/pull/1076. Waiting for it.

**Comment by felickz** [comment]
@JarLob - FYI this is merged!

**Comment by JarLob** [comment]
Could you please try if it works? As I understand no changes are needed in SCS, but it is requires manually modifying OmniSharp settings and it is cumbersome. People could benefit from clear instructions.
