### ISSUE TITLE
TaintAnalyzerCSharp threw an exception while visiting method ProducesResponseType in a project using Swagger

### ISSUE THREAD

**Issue by philipba** [security-code-scan/security-code-scan#81]
Hello,

I'm running the SecurityCodeScan.VS2017 v2.8.0 on an ASP.net Core Web API Application. 

Here are the current packages on the project
`<PackageReference Include="Castle.Core" Version="4.2.1" />`
`<PackageReference Include="Google.Cloud.Diagnostics.AspNetCore" Version="2.0.0" />`
`<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />`
`<PackageReference Include="AutoMapper" Version="7.0.1" />`
`<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="4.0.1" />`
`<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="2.3.0" />`
`<PackageReference Include="morelinq" Version="2.10.0" />`
`<PackageReference Include="RavenSharp.Core" Version="1.0.0-beta-1" />`
`<PackageReference Include="SecurityCodeScan.VS2017" Version="2.8.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>`
`<PackageReference Include="Swashbuckle.AspNetCore" Version="2.5.0" />`
`<PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration.Tools" Version="1.1.0-preview4-final" />`
`<PackageReference Include="Microsoft.DotNet.InternalAbstractions" Version="1.0.0" />`
`<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.2.2" />`

Here is a sample Controller Action in my application

![image](https://user-images.githubusercontent.com/35262440/45535151-19777400-b830-11e8-9982-e4e654f4d246.png)

I'm getting exception related to `ProducesResponseType`

![image](https://user-images.githubusercontent.com/35262440/45535194-3ad86000-b830-11e8-845c-8b72de28e68e.png)

**Comment by JarLob** [comment]
I assume 

> I'm running the SecurityCodeScan.VS2017 **v2.3.0**

 is typo because it is 2.8 in the project...
I have tried several random projects from github with `ProducesResponseType`, but couldn't reproduce.
A minimal reproducible project would help.

**Comment by philipba** [comment]
Yeah' it's 2.3.0, 
I'll try to provide a simpler one.

**Comment by philipba** [comment]
@JarLob actually I noticed on my target project, there's a lot of these unhanded exception warning from the Analyzer (Methods, Classes), however the warning isn't giving details about what wen't wrong exactly. I'll try to replicate this using a different project.

**Comment by philipba** [comment]
Hi Here's a test project you can run. 
[SecurityCodeScanTest.zip](https://github.com/security-code-scan/security-code-scan/files/2387123/SecurityCodeScanTest.zip)
We're getting unhanded exceptions still but in this project we're getting some details on deserialisation issues.

**Comment by philipba** [comment]
I have Visual Studio 15.8.4 
I checked my Extensions and saw "Developer Analytics Tool" is enabled. I disabled it and did a clean and rebuild.
I didn't change anything from that test project. Here's the result
![image](https://user-images.githubusercontent.com/35262440/45608564-402ee800-ba86-11e8-86c7-66eb123e40e6.png)

**Comment by JarLob** [comment]
Do you have the file `C:\Users\{your user name}\AppData\Local\SecurityCodeScan\config-1.0.yml`?

**Comment by philipba** [comment]
That's weird I don't have that file or the `SecurityCodeScan` directory

**Comment by JarLob** [comment]
That's alright. It is optional. I'm checking if you have invalid data in it.

**Comment by JarLob** [comment]
I can be related to #82 Could you try https://www.nuget.org/packages/SecurityCodeScan/ nuget?

**Comment by philipba** [comment]
Sorry for the late reply.
Here's the result
![image](https://user-images.githubusercontent.com/35262440/45997059-fcb12b00-c0d0-11e8-8a6e-f16ed5389693.png)
