### ISSUE TITLE
Unhandled Exception during serialization

### ISSUE THREAD

**Issue by Alucardz** [security-code-scan/security-code-scan#82]
**IDE**: VS 2017 Professional v15.3.8
**Project**: WebGOAT.NET [https://codeload.github.com/OWASP/WebGoat.NET/legacy.zip/master](url)
**Project Target Framework**: 3.5 (or anything above it for that matter)
**Installation Type**: NuGet (not VSIX) SecurityCodeScan.VS2017 v2.8.0

Example Exception (there are 13 other similar ones):

System.Exception: Unhandled exception while visiting method
```
private string SHA(string s, WG_Hash hash)
    	{
    		byte[] bytes = System.Text.ASCIIEncoding.ASCII.GetBytes(s);
			byte[] result;
            HashAlgorithm sha = null;
			switch(hash){
				case WG_Hash.Sha1:
					sha = new SHA1Managed();
			    	break;
				case WG_Hash.Sha256:
					sha = new SHA256Managed();
					break;
			}
			result = sha.ComputeHash(bytes);
			return System.Convert.ToBase64String(result);
    	}
```
(Line: 2, Col: 12, Idx: 48) - (Line: 2, Col: 17, Idx: 53): Exception during deserialization ---> YamlDotNet.Core.YamlException: (Line: 2, Col: 12, Idx: 48) - (Line: 2, Col: 17, Idx: 53): Exception during deserialization ---> System.IO.FileNotFoundException: **Could not load file or assembly 'System.ComponentModel.TypeConverter, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies**. The system cannot find the file specified.
   at YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(Object value, Type destinationType, CultureInfo culture)

I tried installing System.ComponentModel.TypeConverter 4.0.0 as a nuget package, to no avail.

In addition to the following warnings:

```
1>  CSC : warning AD0001: Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method public String Message
1>  CSC : warning AD0001: Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method public CustomerLoginData(string email, string password, bool isLoggedIn)
1>  CSC : warning AD0001: Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method protected void btnUpload_Click(object sender, EventArgs e)
1>  CSC : warning AD0001: Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method protected void Page_Load(object sender, EventArgs e)
1>  CSC : warning AD0001: Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method protected void btnLogout_Click(object sender, EventArgs e)
1>  CSC : warning AD0001: Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method protected void CreateAccountButton_Click(object sender, EventArgs e)
1>  CSC : warning AD0001: Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method protected void Page_Load(object sender, EventArgs e)
1>  CSC : warning AD0001: Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method protected void Page_Load(object sender, EventArgs e)
1>  CSC : warning AD0001: Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method public static bool ResponseFile(HttpRequest _Request, HttpResponse _Response, string _fileName, string _fullPath, long _speed)
```

Any ideas?

I have many other similar problems on another project but I figured I'd isolate the case using WebGOAT.NET to make as reproducible as possible.

**Comment by JarLob** [comment]
Thanks for the tip it might somehow be related to not found dlls...
On my machine I have VS 15.8.4 and can not reproduce. I'll need a clean VM for testing.
You stressed that it is only nuget issue. Is it reproducible with non VS2017 nuget? https://www.nuget.org/packages/SecurityCodeScan/
This nuget should also work with VS2017 on Windows. The  SecurityCodeScan.VS2017 is just for linux builds...

**Comment by Alucardz** [comment]
Thanks for the quick reply!

I thought of upgrading to VS 15.8.4 and testing it (i'll do that in a bit and update you), but I did use the non VS2017 package and the good news is that the list of unhandled exceptions went away, however i'm still faced with 7 cases of AD0001 with the:

`Could not load file or assembly 'System.ComponentModel.TypeConverter, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies`

error.

**Comment by Alucardz** [comment]
Closing VS 2017, cleaning and rebuilding made those errors go away... Even went back to my original project, I'm getting different errors (but much less!), so i'll post them in another issue.
