### ISSUE TITLE
Works on Visual Studio 2015 or higher. Free Visual Studio Community and paid Professional and Enterprise editions are supported.

### ISSUE THREAD

**Issue by GingerDonkey1** [security-code-scan/security-code-scan#9]
Please can you clarify the following statement:

_"Works on Visual Studio 2015 or higher. Free Visual Studio Community and paid Professional and Enterprise editions are supported."_

That appear on https://security-code-scan.github.io/

I, and colleague have Visual Studio 2015 professional.  Do we need to pay any licencing for this extension, or is it completely free to use?

**Comment by JarLob** [comment]
It is open source and free. I referred to Visual Studio editions: Community, Professional, Enterprise.

**Comment by GingerDonkey1** [comment]
Thank you for your help that is great.
