### ISSUE TITLE
NonAction attributes are ignored, causing false positives

### ISSUE THREAD

**Issue by thomasgoldstein** [security-code-scan/security-code-scan#90]
I'm getting warnings such as "SCS0016 - Cross-Site Request Forgery (CSRF)" on a public controller method marked with a [NonAction] attribute (https://docs.microsoft.com/en-us/dotnet/api/system.web.mvc.nonactionattribute?view=aspnet-mvc-5.2).

I believe such controller method warnings should only apply to actual action methods, meaning such security rules should not apply to methods marked as NonAction.

**Comment by JarLob** [comment]
Does the method have any http attribute at the same time?

**Comment by thomasgoldstein** [comment]
No, it does not. The only attribute it has is the NonAction one. Let me know if you'd like me to provide a simple test project that triggers this behavior.

**Comment by JarLob** [comment]
Default action, without an attribute is HttpGet, but the analyzer should skip it. The only hypothesis I have, that there is non-Get action with the same name in the parent class. Reproducible code would help!

**Comment by thomasgoldstein** [comment]
I was wrong, there is an HttpPost on that method. I didn't see it at first sight because it's an overriden method, and the HttpPost attribute is in one of its base classes. So, is that the expected behavior then?

Simplified controller (.NET Framework, not Core):

```
using System.Web.Mvc;

namespace ScsTestApp
{
    public class TestController : System.Web.Http.ApiController
    {
        [HttpPost]
        [NonAction]
        public void Post(string value)
        {
        }
    }
}
```

**Comment by JarLob** [comment]
The issue is valid, there should be no warning if it is not an action.
